package br.com.petshow.model;

public class GroupMembers {
	
/*
 * create table group_members (
  id bigint generated by default as identity(start with 0) primary key,
  username varchar(50) not null,
  group_id bigint not null,
  constraint fk_group_members_group foreign key(group_id) references groups(id));
 * 	
 */
	
	//https://docs.spring.io/spring-security/site/docs/3.0.x/reference/springsecurity.pdf

}
