package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosPiaui {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|  Teresina",
				"2|  Parnaíba",
				"3|  Picos",
				"4|  Piripiri",
				"5|  Floriano",
				"6|  Barras",
				"7|  Campo Maior",
				"8|  União",
				"9|  Altos",
				"10| Esperantina",
				"11| José de Freitas",
				"12| Pedro II",
				"13| Oeiras",
				"14| São Raimundo Nonato",
				"15| Miguel Alves",
				"16| Luís Correia",
				"17| Piracuruca",
				"18| Cocal",
				"19| Batalha",
				"20| Corrente",
				"21| Luzilândia",
				"22| Bom Jesus",
				"23| Uruçuí",
				"24| Canto do Buriti",
				"25| Valença do Piauí",
				"26| São João do Piauí",
				"27| Paulistana",
				"28| Buriti dos Lopes",
				"29| Castelo do Piauí",
				"30| Jaicós",
				"31| Pio IX",
				"32| Regeneração",
				"33| São Miguel do Tapuio",
				"34| Amarante",
				"35| Água Branca",
				"36| Inhuma",
				"37| Elesbão Veloso",
				"38| Simões",
				"39| Palmeirais",
				"40| Joaquim Pires",
				"41| Alto Longá",
				"42| São Pedro do Piauí",
				"43| Demerval Lobão",
				"44| Simplício Mendes",
				"45| Porto",
				"46| Pimenteiras",
				"47| Avelino Lopes",
				"48| Fronteiras",
				"49| Itainópolis",
				"51| Baixa Grande do Ribeiro",
				"52| Capitão de Campos",
				"53| Curimatá",
				"54| Itaueira",
				"55| Matias Olímpio",
				"56| Caracol",
				"57| Parnaguá",
				"58| Gilbués",
				"59| Monte Alegre do Piauí",
				"60| Monsenhor Gil",
				"61| Cabeceiras do Piauí",
				"62| Guadalupe",
				"63| Cristino Castro",
				"64| Beneditinos",
				"65| Sigefredo Pacheco",
				"66| Anísio de Abreu",
				"67| Ipiranga do Piauí",
				"68| Dom Inocêncio",
				"69| Ilha Grande",
				"70| Francisco Santos",
				"71| Murici dos Portelas",
				"72| Queimada Nova",
				"73| Redenção do Gurgueia",
				"74| Nossa Senhora dos Remédios",
				"75| Isaías Coelho",
				"76| Nazária",
				"77| Lagoa Alegre",
				"78| Marcolândia",
				"79| Brasileira",
				"80| Madeiro",
				"81| Cristalândia do Piauí",
				"82| Buriti dos Montes",
				"83| São João do Arraial",
				"84| Assunção do Piauí",
				"85| Monsenhor Hipólito",
				"86| Colônia do Piauí",
				"87| Alagoinha do Piauí",
				"88| Cajueiro da Praia",
				"89| Nazaré do Piauí",
				"91| Ribeiro Gonçalves",
				"92| Campo Largo do Piauí",
				"93| Acauã",
				"94| Barro Duro",
				"95| Dirceu Arcoverde",
				"96| Dom Expedito Lopes",
				"97| Padre Marcos",
				"98| Angical do Piauí",
				"99| Morro do Chapéu do Piauí",
				"100|Boa Hora",
				"101|Lagoa de São Francisco",
				"102|São José do Piauí",
				"103|Sussuapara",
				"104|Milton Brandão",
				"105|Novo Oriente do Piauí",
				"106|Colônia do Gurgueia",
				"107|Massapê do Piauí",
				"108|Rio Grande do Piauí",
				"109|São Francisco do Piauí",
				"110|Boqueirão do Piauí",
				"111|Patos do Piauí",
				"112|Santo Antônio de Lisboa",
				"113|São Julião",
				"114|Santa Filomena",
				"115|Santa Cruz do Piauí",
				"116|Betânia do Piauí",
				"117|São João da Serra",
				"118|Cocal dos Alves",
				"119|São João da Fronteira",
				"120|Campo Grande do Piauí",
				"121|São Francisco de Assis do Piauí",
				"122|Aroazes",
				"123|Caraúbas do Piauí",
				"124|Santa Luz",
				"125|Caldeirão Grande do Piauí",
				"126|Jacobina do Piauí",
				"127|Bonfim do Piauí",
				"128|Júlio Borges",
				"129|Bom Princípio do Piauí",
				"130|Campinas do Piauí",
				"131|Bertolínia",
				"132|Juazeiro do Piauí",
				"133|Geminiano",
				"134|Joca Marques",
				"135|Caxingó",
				"136|Alvorada do Gurgueia",
				"137|Francinópolis",
				"138|Manoel Emídio",
				"139|São José do Divino",
				"140|Landri Sales",
				"141|Fartura do Piauí",
				"142|Santa Rosa do Piauí",
				"143|Curral Novo do Piauí",
				"144|Agricolândia",
				"145|Lagoa do Sítio",
				"146|Caridade do Piauí",
				"147|Palmeira do Piauí",
				"148|Campo Alegre do Fidalgo",
				"149|São Gonçalo do Piauí",
				"150|Várzea Branca",
				"151|Currais",
				"152|Alegrete do Piauí",
				"153|Eliseu Martins",
				"154|Cocal de Telha",
				"155|Jatobá do Piauí",
				"156|Nossa Senhora de Nazaré",
				"157|São João da Varjota",
				"158|Jurema",
				"159|Arraial",
				"160|Coronel José Dias",
				"161|Lagoa do Barro do Piauí",
				"162|Santana do Piauí",
				"163|Conceição do Canindé",
				"164|São João da Canabrava",
				"165|Socorro do Piauí",
				"166|São Lourenço do Piauí",
				"167|Passagem Franca do Piauí",
				"168|Guaribas",
				"169|Marcos Parente",
				"170|Bocaina",
				"171|Jardim do Mulato",
				"172|Flores do Piauí",
				"173|Ribeira do Piauí",
				"174|Jerumenha",
				"175|Wall Ferraz",
				"176|São Braz do Piauí",
				"177|Curralinhos",
				"178|Várzea Grande",
				"179|Francisco Ayres",
				"180|Nova Santa Rita",
				"181|Domingos Mourão",
				"182|Riacho Frio",
				"183|Sebastião Leal",
				"184|Morro Cabeça no Tempo",
				"185|Paes Landim",
				"186|Capitão Gervásio Oliveira",
				"187|Lagoa do Piauí",
				"188|Pau-d'Arco do Piauí",
				"189|Coivaras",
				"190|Santa Cruz dos Milagres",
				"191|Bela Vista do Piauí",
				"192|Canavieira",
				"193|Paquetá",
				"194|Barra d'Alcântara",
				"195|Brejo do Piauí",
				"196|Hugo Napoleão",
				"197|Santo Inácio do Piauí",
				"198|São José do Peixe",
				"199|Pavussu",
				"200|Belém do Piauí",
				"201|Cajazeiras do Piauí",
				"202|Sebastião Barros",
				"203|Pajeú do Piauí",
				"204|Barreiras do Piauí",
				"205|Francisco Macedo",
				"206|Antônio Almeida",
				"207|Prata do Piauí",
				"208|Vera Mendes",
				"209|São Miguel do Fidalgo",
				"210|São Gonçalo do Gurgueia",
				"211|João Costa",
				"212|Vila Nova do Piauí",
				"213|Novo Santo Antônio",
				"214|São Félix do Piauí",
				"215|Tamboril do Piauí",
				"216|Lagoinha do Piauí",
				"217|Tanque do Piauí",
				"218|Porto Alegre do Piauí",
				"219|São Luis do Piauí",
				"220|Floresta do Piauí",
				"221|Pedro Laurentino",
				"222|Aroeiras do Itaim",
				"223|São Miguel da Baixa Grande",
				"224|Olho d'Água do Piauí",
				"225|Santo Antônio dos Milagres",
				"226|Miguel Leão"
				
		);
		return municipios;
	}
	

}


