package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosPara {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|  Belém ",
				"2|  Ananindeua ",
				"3|  Santarém ",
				"4|  Marabá ",
				"5|  Parauapebas ",
				"6|  Castanhal ",
				"7|  Abaetetuba ",
				"8|  Cametá ",
				"9|  Marituba ",
				"10| São Félix do Xingu ",
				"11| Bragança ",
				"12| Barcarena ",
				"13| Altamira ",
				"14| Tucuruí ",
				"15| Paragominas ",
				"16| Tailândia ",
				"17| Breves ",
				"18| Itaituba ",
				"19| Redenção ",
				"20| Moju ",
				"21| Novo Repartimento ",
				"22| Oriximiná ",
				"23| Santana do Araguaia ",
				"24| Santa Isabel do Pará ",
				"25| Capanema ",
				"26| Breu Branco ",
				"27| Ipixuna do Pará ",
				"28| Tomé-Açu ",
				"29| Igarapé-Miri ",
				"30| Benevides ",
				"31| Portel ",
				"32| Viseu ",
				"33| Dom Eliseu ",
				"34| Jacundá ",
				"35| Ulianópolis ",
				"36| São Miguel do Guamá ",
				"37| Monte Alegre ",
				"38| Juruti ",
				"39| Alenquer ",
				"40| Acará ",
				"41| Capitão Poço ",
				"42| Vigia ",
				"43| Itupiranga ",
				"44| Rondon do Pará ",
				"45| Óbidos ",
				"47| Rurópolis ",
				"48| Conceição do Araguaia ",
				"49| Pacajá ",
				"51| Baião ",
				"52| Augusto Corrêa ",
				"53| Uruará ",
				"54| Xinguara ",
				"55| Porto de Moz ",
				"56| Salinópolis ",
				"57| Goianésia do Pará ",
				"58| Muaná ",
				"59| Curuçá ",
				"60| Tucumã ",
				"61| Afuá ",
				"62| Igarapé-Açu ",
				"63| Canaã dos Carajás ",
				"64| Curralinho ",
				"65| Almeirim ",
				"66| Cachoeira do Piriá ",
				"67| Eldorado dos Carajás ",
				"68| Gurupá ",
				"69| Concórdia do Pará ",
				"70| Ourilândia do Norte ",
				"71| Irituia ",
				"72| Oeiras do Pará ",
				"73| São Domingos do Capim ",
				"74| Medicilândia ",
				"75| Santo Antônio do Tauá ",
				"76| Aurora do Pará ",
				"77| Mocajuba ",
				"78| Ponta de Pedras ",
				"79| Placas ",
				"80| Tracuateua ",
				"81| Bagre ",
				"82| Mãe do Rio ",
				"83| Prainha ",
				"84| Maracanã ",
				"85| Anajás ",
				"86| Bujaru ",
				"87| Limoeiro do Ajuru ",
				"88| Marapanim ",
				"89| Anapu ",
				"91| Melgaço ",
				"92| Água Azul do Norte ",
				"93| São Sebastião da Boa Vista ",
				"94| Garrafão do Norte ",
				"95| Novo Progresso ",
				"96| São Domingos do Araguaia ",
				"97| Soure ",
				"98| São Geraldo do Araguaia ",
				"99| Santa Maria do Pará ",
				"100|Cachoeira do Arari ",
				"101|Salvaterra ",
				"102|Chaves ",
				"103|São João de Pirabas ",
				"104|Santa Maria das Barreiras ",
				"105|Nova Esperança do Piriá ",
				"106|Santa Bárbara do Pará ",
				"107|Floresta do Araguaia ",
				"108|Santa Luzia do Pará ",
				"109|Trairão ",
				"110|Terra Santa ",
				"111|Rio Maria ",
				"112|São Caetano de Odivelas ",
				"113|Curionópolis ",
				"114|Ourém ",
				"115|Belterra ",
				"116|Bom Jesus do Tocantins ",
				"117|Nova Ipixuna ",
				"118|Aveiro ",
				"119|Bonito ",
				"120|Mojuí dos Campos ",
				"121|São Francisco do Pará ",
				"122|Nova Timboteua ",
				"123|Vitória do Xingu ",
				"124|Brasil Novo ",
				"125|Curuá ",
				"126|São João do Araguaia ",
				"127|Quatipuru ",
				"128|Cumaru do Norte ",
				"129|Piçarra ",
				"130|Colares ",
				"131|Senador José Porfírio ",
				"132|Terra Alta ",
				"133|Inhangapi ",
				"134|Primavera ",
				"135|Santa Cruz do Arari ",
				"136|Magalhães Barata ",
				"137|Jacareacanga ",
				"138|Peixe-Boi ",
				"139|Palestina do Pará ",
				"140|Brejo Grande do Araguaia ",
				"141|Abel Figueiredo ",
				"142|Faro ",
				"143|Santarém Novo ",
				"144|São João da Ponta ",
				"145|Sapucaia ",
				"146|Pau-d'Arco ",
				"147|Bannach "
		);
		return municipios;
	}
	

}


