package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosMatoGrosso {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|  Cuiabá",
				"2|  Várzea Grande",
				"3|  Rondonópolis",
				"4|  Sinop",
				"5|  Tangará da Serra",
				"6|  Cáceres",
				"7|  Sorriso",
				"8|  Lucas do Rio Verde",
				"9|  Primavera do Leste",
				"10| Barra do Garças",
				"11| Alta Floresta",
				"12| Pontes e Lacerda",
				"13| Nova Mutum",
				"14| Campo Verde",
				"15| Juína",
				"16| Colniza",
				"17| Guarantã do Norte",
				"18| Juara",
				"19| Barra do Bugres",
				"20| Peixoto de Azevedo",
				"21| Campo Novo do Parecis",
				"22| Colíder",
				"23| Poconé",
				"24| Confresa",
				"25| Mirassol d'Oeste",
				"26| Jaciara",
				"27| Vila Rica",
				"28| Água Boa",
				"29| Sapezal",
				"30| Paranatinga",
				"31| Aripuanã",
				"32| Diamantino",
				"33| Nova Xavantina",
				"34| Canarana",
				"35| Comodoro",
				"36| São José do Rio Claro",
				"37| Nova Olímpia",
				"38| Chapada dos Guimarães",
				"39| Cotriguaçu",
				"40| Brasnorte",
				"41| São José dos Quatro Marcos",
				"42| Santo Antônio do Leverger",
				"43| Alto Araguaia",
				"44| Pedra Preta",
				"45| Rosário Oeste",
				"46| Querência",
				"47| Araputanga",
				"48| Poxoréu",
				"49| Matupá",
				"51| Vila Bela da Santíssima Trindade",
				"52| Campinápolis",
				"53| Nobres",
				"54| Juruena",
				"55| Guiratinga",
				"56| Nova Bandeirantes",
				"57| Feliz Natal",
				"58| Tapurah",
				"59| Itiquira",
				"60| Nossa Senhora do Livramento",
				"61| Nova Canaã do Norte",
				"62| Porto Alegre do Norte",
				"63| Cláudia",
				"64| Porto Esperidião",
				"65| Alto Garças",
				"66| Nova Ubiratã",
				"67| São Félix do Araguaia",
				"68| Juscimeira",
				"69| Alto Paraguai",
				"70| Vera",
				"71| Paranaíta",
				"72| Marcelândia",
				"73| Carlinda",
				"74| Alto Taquari",
				"75| Ribeirão Cascalheira",
				"76| Apiacás",
				"77| Terra Nova do Norte",
				"78| Arenápolis",
				"79| Tabaporã",
				"80| Denise",
				"81| Nova Monte Verde",
				"82| Jauru",
				"83| Novo Mundo",
				"84| Castanheira",
				"85| Nova Maringá",
				"86| Santa Terezinha",
				"87| Jangada",
				"88| Dom Aquino",
				"89| Barão de Melgaço",
				"91| Gaúcha do Norte",
				"92| Ipiranga do Norte",
				"93| Campos de Júlio",
				"94| Alto Boa Vista",
				"95| Itanhangá",
				"96| Pontal do Araguaia",
				"97| Nova Lacerda",
				"98| Bom Jesus do Araguaia",
				"99| Nortelândia",
				"100|Lambari d'Oeste",
				"101|Cocalinho",
				"102|São José do Xingu",
				"103|General Carneiro",
				"104|Porto dos Gaúchos",
				"105|Acorizal",
				"106|Novo São Joaquim",
				"107|Curvelândia",
				"108|Rio Branco",
				"109|Santo Antônio do Leste",
				"110|Canabrava do Norte",
				"111|São Pedro da Cipa",
				"112|Nova Guarita",
				"113|Santa Carmem",
				"114|São José do Povo",
				"115|Novo Horizonte do Norte",
				"116|Conquista d'Oeste",
				"117|Rondolândia",
				"118|Nova Brasilândia",
				"119|Itaúba",
				"120|Tesouro",
				"121|Nova Nazaré",
				"122|Nova Santa Helena",
				"123|Torixoréu",
				"124|União do Sul",
				"125|Figueirópolis d'Oeste",
				"126|Salto do Céu",
				"127|Santa Rita do Trivelato",
				"128|Nova Marilândia",
				"129|Santo Afonso",
				"130|Vale de São Domingos",
				"131|Araguaiana",
				"132|Porto Estrela",
				"133|Glória d'Oeste",
				"134|Indiavaí",
				"135|Reserva do Cabaçal",
				"136|Planalto da Serra",
				"137|Novo Santo Antônio",
				"138|Santa Cruz do Xingu",
				"139|Ribeirãozinho",
				"140|Luciara",
				"141|Serra Nova Dourada",
				"142|Ponte Branca",
				"143|Araguainha"
		);
		return municipios;
	}
	

}


