package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosGoias {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|  Goiânia  ",
				"2|  Aparecida de Goiânia  ",
				"3|    ",
				"4|  Anápolis  ",
				"5|  Rio Verde  ",
				"6|    ",
				"7|  Luziânia  ",
				"8|  Águas Lindas de Goiás  ",
				"9|  Valparaíso de Goiás  ",
				"10| Trindade  ",
				"11|   Formosa  ",
				"12|   Novo Gama  ",
				"13|   Senador Canedo  ",
				"14|   Itumbiara  ",
				"15|   Catalão  ",
				"16|   ",
				"17| Jataí  ",
				"18| Planaltina  ",
				"19| Caldas Novas  ",
				"20| Santo Antônio do Descoberto  ",
				"21| Goianésia  ",
				"22| Cidade Ocidental  ",
				"23| Mineiros  ",
				"24| Cristalina  ",
				"25| Inhumas  ",
				"26|   ",
				"27| Quirinópolis  ",
				"28| Jaraguá  ",
				"29| Niquelândia  ",
				"30| Porangatu  ",
				"31| Morrinhos  ",
				"32| Goianira  ",
				"33| Itaberaí  ",
				"34| Uruaçu  ",
				"35| Santa Helena de Goiás  ",
				"36| Posse  ",
				"37| Goiatuba  ",
				"38| São Luís de Montes Belos  ",
				"39| Iporá  ",
				"40| Padre Bernardo  ",
				"41| Pires do Rio  ",
				"42| Minaçu  ",
				"43|   ",
				"44| Bela Vista de Goiás  ",
				"45| Nerópolis  ",
				"46| Palmeiras de Goiás  ",
				"47| Itapuranga  ",
				"48| Ipameri  ",
				"49| Alexânia  ",
				"51| Anicuns  ",
				"52| Piracanjuba  ",
				"53| Pirenópolis  ",
				"54| Goiás  ",
				"55| Bom Jesus de Goiás  ",
				"56| São Miguel do Araguaia  ",
				"57| Ceres  ",
				"58| Acreúna  ",
				"59| Itapaci  ",
				"60| Silvânia  ",
				"61| Hidrolândia  ",
				"62|   ",
				"63| Rubiataba  ",
				"64| Aragarças  ",
				"65| Campos Belos  ",
				"66| São Simão  ",
				"67| Cocalzinho de Goiás  ",
				"68| Jussara  ",
				"69| Abadiânia  ",
				"70| Caiapônia  ",
				"71| Pontalina  ",
				"72| Crixás  ",
				"73| Orizona  ",
				"74| Caçu  ",
				"75| Indiara  ",
				"76| Mozarlândia  ",
				"77| Flores de Goiás  ",
				"78| Guapó  ",
				"79| Uruana  ",
				"80| Vianópolis  ",
				"81| Iaciara  ",
				"82| Maurilândia  ",
				"83| Firminópolis  ",
				"84| Nova Crixás  ",
				"85| São Domingos  ",
				"86| São João d'Aliança  ",
				"87| Montividiu  ",
				"88| Campinorte  ",
				"89| Edeia  ",
				"91| Cachoeira Alta  ",
				"92| Goianápolis  ",
				"93| Paraúna  ",
				"94| Piranhas  ",
				"95| Corumbá de Goiás  ",
				"96| Rialma  ",
				"97| Petrolina de Goiás  ",
				"98| Mara Rosa  ",
				"99| Barro Alto  ",
				"100|  ",
				"101|Paranaiguara  ",
				"102|Cavalcante  ",
				"103|Carmo do Rio Verde  ",
				"104|Santa Terezinha de Goiás  ",
				"105|Aragoiânia  ",
				"106|Buriti Alegre  ",
				"107|Nova Veneza  ",
				"108|Corumbaíba  ",
				"109|Itauçu  ",
				"110|Aruanã  ",
				"111|Bonfinópolis  ",
				"112|Bom Jardim de Goiás  ",
				"113|Chapadão do Céu  ",
				"114|Nazário  ",
				"115|Alvorada do Norte  ",
				"116|Nova Glória  ",
				"117|Monte Alegre de Goiás  ",
				"118|Cachoeira Dourada  ",
				"119|Cezarina  ",
				"120|Vicentinópolis  ",
				"121|Serranópolis  ",
				"122|Montes Claros de Goiás  ",
				"123|Mambaí  ",
				"124|Santa Rita do Araguaia  ",
				"125|Abadia de Goiás  ",
				"126|Cabeceiras  ",
				"127|Araguapaz  ",
				"128|Doverlândia  ",
				"129|Sanclerlândia  ",
				"130|Leopoldo de Bulhões  ",
				"131|Terezópolis de Goiás  ",
				"132|Alto Paraíso de Goiás  ",
				"133|Joviânia  ",
				"134|Campo Limpo de Goiás  ",
				"135|Campo Alegre de Goiás  ",
				"136|Faina  ",
				"137|Itarumã  ",
				"138|Simolândia  ",
				"139|Itapirapuã  ",
				"140|São Francisco de Goiás  ",
				"141|Santa Bárbara de Goiás  ",
				"142|Jandaia  ",
				"143|Ouvidor  ",
				"144|Fazenda Nova  ",
				"145|Inaciolândia  ",
				"146|Americano do Brasil  ",
				"147|Britânia  ",
				"148|Mundo Novo  ",
				"149|Santo Antônio de Goiás  ",
				"150|Vila Propício  ",
				"151|Alto Horizonte  ",
				"152|Vila Boa  ",
				"153|Goiandira  ",
				"154|Gouvelândia  ",
				"155|Água Fria de Goiás  ",
				"156|Itaguaru  ",
				"157|Santa Fé de Goiás  ",
				"158|São Luís do Norte  ",
				"159|Caturaí  ",
				"160|Divinópolis de Goiás  ",
				"161|Turvelândia  ",
				"162|Itajá  ",
				"163|Turvânia  ",
				"164|Rianápolis  ",
				"165|Mossâmedes  ",
				"166|Santo Antônio da Barra  ",
				"167|Itaguari  ",
				"168|Formoso  ",
				"169|Baliza  ",
				"170|Matrinchã  ",
				"171|Montividiu do Norte  ",
				"172|Novo Planalto  ",
				"173|Guarani de Goiás  ",
				"174|Aporé  ",
				"175|Bonópolis  ",
				"176|Portelândia  ",
				"177|Rio Quente  ",
				"178|São Miguel do Passa-Quatro  ",
				"179|Ouro Verde de Goiás  ",
				"180|Mutunópolis  ",
				"181|Hidrolina  ",
				"182|Santa Isabel  ",
				"183|Varjão  ",
				"184|Edealina  ",
				"185|Santa Tereza de Goiás  ",
				"186|Araçu  ",
				"187|Heitoraí  ",
				"188|Campinaçu  ",
				"189|Amaralina  ",
				"190|Gameleira de Goiás  ",
				"191|Porteirão  ",
				"192|Caldazinha  ",
				"193|Palminópolis  ",
				"194|Campos Verdes  ",
				"195|Castelândia  ",
				"196|Taquaral de Goiás  ",
				"197|Cromínia  ",
				"198|Campestre de Goiás  ",
				"199|Trombas  ",
				"200|Brazabrantes  ",
				"201|Colinas do Sul  ",
				"202|Palestina de Goiás  ",
				"203|Aurilândia  ",
				"204|Nova Roma  ",
				"205|Amorinópolis  ",
				"206|Buritinópolis ",
				"207|Damianópolis  ",
				"208|Estrela do Norte (Goiás)  ",
				"209|Professor Jamil  ",
				"210|Santa Rita do Novo Destino  ",
				"211|Teresina de Goiás  ",
				"212|Novo Brasil  ",
				"213|Urutaí  ",
				"214|Perolândia  ",
				"215|Santa Cruz de Goiás  ",
				"216|Cristianópolis  ",
				"217|Jaupaci  ",
				"218|Arenópolis  ",
				"219|Sítio d'Abadia  ",
				"220|Cumari  ",
				"221|Uirapuru  ",
				"222|Nova Iguaçu de Goiás  ",
				"223|Ipiranga de Goiás  ",
				"224|Damolândia  ",
				"225|Israelândia  ",
				"226|Três Ranchos  ",
				"227|Panamá  ",
				"228|Mimoso de Goiás  ",
				"229|Santa Rosa de Goiás  ",
				"230|Buriti de Goiás  ",
				"231|Ivolândia  ",
				"232|Pilar de Goiás  ",
				"233|Adelândia  ",
				"234|Diorama  ",
				"235|Córrego do Ouro  ",
				"236|Aparecida do Rio Doce  ",
				"237|Avelinópolis  ",
				"238|Jesúpolis  ",
				"239|Mairipotaba  ",
				"240|Palmelo  ",
				"241|Nova América  ",
				"242|Morro Agudo de Goiás  ",
				"243|Guaraíta  ",
				"244|Marzagão  ",
				"245|Nova Aurora  ",
				"246|Davinópolis  ",
				"247|Guarinos  ",
				"248|Aloândia  ",
				"249|São Patrício  ",
				"250|Água Limpa  ",
				"251|Moiporá  ",
				"252|São João da Paraúna  ",
				"253|Lagoa Santa  ",
				"254|Cachoeira de Goiás  ",
				"255|Anhanguera  "
			
		);
		return municipios;
	}
	

}


