package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;

public class JobCadRacas {
	
	
	public static List<String> getRacasCachorro() {
		List<String> cachorros = Arrays.asList(
				"SRD (vira-lata)         ",
				"Afghan Hound            ",
				"Airedale Terrier         ",
				"Akita-Inu                ",
				"American Staf.Terrier    ",
				"Australian Cattle Dog    ",
				"Basenji                  ",
				"Basset Hound             ",
				"Beagle                   ",
				"Bernese M. Dog          ",
				"Bichon Frise            ",
				"Bloodhound              ",
				"Border Collie           ",
				"Borzoi                  ",
				"Boston Terrier          ",
				"Bouvier de Flandres     ",
				"Boxer                   ",
				"Braco Alemão            ",
				"Buldogue Americano      ",
				"Buldogue Francês        ",
				"Buldogue Inglês         ",
				"Bull Terrier            ",
				"Bulmastife              ",
				"Cairn Terrier           ",
				"Cane Corso              ",
				"Cavalier K.C.Spaniel    ",
				"Chihuahua               ",
				"Chinese Crested Dog     ",
				"Chow-Chow               ",
				"Cocker Spaniel          ",
				"Collie                  ",
				"Coton de Tulear         ",
				"Dalmata                 ",
				"Daschund (Salsicha)     ",
				"Dobermann               ",
				"Dogo Argentino          ",
				"Dogue Alemão            ",
				"Dogue Brasileiro        ",
				"Dogue e Bordeaux        ",
				"Fila Brasileiro         ",
				"Fox Paulistinha         ",
				"Fox Terrier             ",
				"Golden Retriever        ",
				"Grande Cão Japones      ",
				"Griffon de Bruxelas     ",
				"Husky Siberiano         ",
				"Jack Russel Terrier     ",
				"Japanese Chin           ",
				"Kuvasz                  ",
				"Labrador                ",
				"Lhasa Apso              ",
				"Lulu Da Pomerânia       ",
				"Malamute do Alaska      ",
				"Maltês                  ",
				"Marrilux                ",
				"Mastife                 ",
				"Mastim Napolitano       ",
				"Old English Sheepdog    ",
				"Pastor Alemão           ",
				"Pastor Alemão Branco    ",
				"Pastor Australiano      ",
				"Pastor Belga            ",
				"Pastor de Shetland      ",
				"Pequeno Lebrel Italiano ",
				"Pequinês                ",
				"Pinscher                ",
				"Pit Bull Terrier        ",
				"Pointer Inglês          ",
				"Poodle                  ",
				"Pug                     ",
				"Rhodesian Ridgeback     ",
				"Rottweiler              ",
				"Saluki                  ",
				"Samoieda                ",
				"São Bernardo            ",
				"Schipperke              ",
				"Schnauzer               ",
				"Scottish Terrier        ",
				"Setter Irlandês         ",
				"Shar Pei                ",
				"Shiba                   ",
				"Shih Tzu                ",
				"Spitz Alemão            ",
				"Springer S. Inglês      ",
				"Stafford Bull Terrier   ",
				"Terra Nova              ",
				"Terrier Brasileiro      ",
				"Terrier Negro Russo     ",
				"Weimaraner              ",
				"Welsh Corgi Pembroke    ",
				"West High W.Terrier     ",
				"Whippet                 ",
				"Yorkshire               "
			
				);
		return cachorros;
	}
	
	public static List<String> getRacasGato() {
		List<String> gatos = Arrays.asList(
				"SRD (Sem raça)             ",
				"Abissínio                  ",
				"Angorá                     ",
				"Balinês                    ",
				"Bengali                    ",
				"Bobtail Japonês            ",
				"British Shorthair         ",
				"Burmilla                  ",
				"California Malhado        ",
				"Chartreux                 ",
				"Cornish Rex               ",
				"Devon Rex                 ",
				"Doméstico                 ",
				"Exótico                   ",
				"German Rex                ",
				"Korat                     ",
				"La Perm                   ",
				"Maine Coon                ",
				"Manx                      ",
				"Mau Egípcio               ",
				"Munchkin                  ",
				"Norueguês da Floresta     ",
				"Oriental                  ",
				"Pêlo Curto Europeu        ",
				"Pêlo Longo Colourpoint    ",
				"Persa                     ",
				"Pixie Bob                 ",
				"Ragdoll                   ",
				"Russian blue              ",
				"Sagrado da Birmânia       ",
				"Scottish Fold             ",
				"Siamês                    ",
				"Singapura                 ",
				"Somali                    ",
				"Sphynx                    ",
				"Tiffanie                  ",
				"Tonquinês                 ",
				"Van Turco                 "
				);
		
		return gatos;
	}
	
	public static List<String> getRacasDeCavalo() {
		List<String> cavalos = Arrays.asList(                                       
				"Abissínio (Etiópia)                                                ",
				"Abtenauer (Austria)                                                ",
				"Aegidienberger (Alemanha)                                          ",
				"Akhal-Teke (Turcomenistão)                                         ",
				"Albanês /  Kali shqiptar (Albânia)                                 ",
				"Altai (Ásia Central)                                               ",
				"Alter-Real (Portugal)                                              ",
				"American Cream Draft (EUA)                                         ",
				"American Indian Horse (EUA)                                        ",
				"American Paint Horse (EUA)                                         ",
				"American Warmblood (EUA)                                           ",
				"Andravida (EUA)                                                    ",
				"Andaluz (Andaluzia, Espanha)                                       ",
				"Adenberg-Nordkirchen (Alemanha)                                    ",
				"Anglo-Árabe (Reino Unido)                                          ",
				"Anglo-Árabe Sardo (Reino Unido)                                    ",
				"Anglo-Kabarda (Reino Unido)                                        ",
				"Appaloosa (EUA)                                                    ",
				"AraAppaloosa (EUA)                                                 ",
				"Árabe (Península Arábica)                                          ",
				"Árabo-frísio (Países Baixos)                                       ",
				"Ardennais (França)                                                 ",
				"Asturcón (Espanha)                                                 ",
				"Australian Draught Horse (Australia)                               ",
				"Australian Stock Horse (Australia)                                 ",
				"Auvergne (França)                                                  ",
				"Auxois (França)                                                    ",
				"Avelin (Itália)                                                    ",
				"Azerbaijano ( Azerbaijão)                                          ",
				"Azteca (México)                                                    ",
				"Baise (china)                                                      ",
				"Balear (Espanha)                                                   ",
				"Baixadeiro (Brasil)                                                ",
				"Balikun (China)                                                    ",
				"Baluchi (Paquistão)                                                ",
				"Banker (EUA)                                                       ",
				"Bávaro (Alemanha)                                                  ",
				"Bardigiano (Itália)                                                ",
				"Basco de Montanha (Espanha)                                        ",
				"Berbere (Magreb)                                                   ",
				"Bhutia (Índia)                                                     ",
				"Bielorruso de Tiro (Bielorússia)                                   ",
				"Blazer (EUA)                                                       ",
				"Boulonnais (França)                                                ",
				"Brabant Belga (Bélgica)                                            ",
				"Brandenburger (Alemanha)                                           ",
				"Brasileiro de hipismo                                              ",
				"Bretão (Bretanha, França)                                          ",
				"Brumby (Australia)                                                 ",
				"Budyonny (Rússia)                                                  ",
				"Burguete (Espanha)                                                 ",
				"Cabardino (Rússia)                                                 ",
				"Calabrês (Itália)                                                  ",
				"Campeiro (Brasil)                                                  ",
				"Campolina (Brasil)                                                 ",
				"Clydesdale (Reino Unido)                                           ",
				"Crioulo (Rio Grande do Sul, Brasil)                                ",
				"Drum (Estados Unidos)                                              ",
				"Falabella (Argentina)                                              ",
				"Floresta Negra (Alemanha)                                          ",
				"Frísio (Países Baixos)                                             ",
				"Garrano (Portugal)                                                 ",
				"Gypsy Vanner (Reino Unido)                                         ",
				"Heck (Alemanha)                                                    ",
				"Haflinger (Áustria)                                                ",
				"Holsteiner (Alemanha)                                              ",
				"isabel (portugal)                                                  ",
				"Islandês (Islândia)                                                ",
				"Konik (Polônia)                                                    ",
				"Lipizzan (Eslovênia)                                               ",
				"Losino (Espanha)                                                   ",
				"Kabarda (Rússia e Geórgia)                                         ",
				"Mangalarga marchador (Minas Gerais, Brasil)                        ",
				"Mangalarga paulista (São Paulo, Brasil)                            ",
				"Marajoara (Ilha de Marajó/Pará, Brasil)                            ",
				"Maremmano (Itália)                                                 ",
				"Marismeño (Espanha)                                                ",
				"Monterufolino (Itália)                                             ",
				"Mustang (selvagem) (América do Norte)                              ",
				"Noriker (Austria)                                                  ",
				"Oldemburgo (Alemanha)                                              ",
				"Paint Horse (EUA)                                                  ",
				"Palomino (portugal)                                                ",
				"Pantaneiro (Brasil)                                                ",
				"Pampa (Brasil)                                                     ",
				"Percheron (Le Perche, França)                                      ",
				"Peruano de passo (Peru)                                            ",
				"Poitevin (França)                                                  ",
				"Pônei brasileiro (Brasil)                                          ",
				"Pônei de Dülmen (Alemanha)                                         ",
				"Pônei Shetland (Reino Unido)                                       ",
				"Pura Raça Galega (PRG) (Espanha)                                   ",
				"Puro-sangue inglês (Inglaterra, Reino Unido)                       ",
				"Puro-sangue lusitano (Portugal)                                    ",
				"Quarto de milha (EUA)                                              ",
				" Saddlebred americano (EUA)                                        ",
		        "Shire (Reino Unido)                                                ",
				"Selle français (França)                                            ",
				" Sorraia (Portugal)                                                ",
				" Suffolk Punch (Reino Unido)										"
			);
				
		return cavalos;
	}         
	
	public static List<String> getRacasDePassaro() {
		List<String> passaros = Arrays.asList(
			    " Agapórnis ",
			    " Araponga",
			    " Canário ",
			    " Calafate", 
				" Periquito Australiano ",
				" Calopsita ",
				" Diamant Gould ",
				" Mandarim  ",
				" Manon  ",
				" Periquito Australiano  ",
				" Periquito Inglês  ",
				" Galo Campina  "
			);
		return passaros;
	}
                
}
