package br.com.petmooby.core.jobs;

import java.util.Arrays;
import java.util.List;

public class JobCadMunicipiosCeara {
	
	
	public static List<String> getMunicipiosCE() {

		List<String> municipios = Arrays.asList("1|Fortaleza	",
				"2|Caucaia	",
				"3|Juazeiro do Norte",
				"4|Maracanaú	",
				"5|Sobral",
				"6|Crato"	,
				"7|Itapipoca",
				"8|Maranguape",
				"9|Iguatu",	
				"10|Quixadá	",
				"11|Pacatuba	",
				"12|Aquiraz	",
				"13|Quixeramobim",
				"14|Canindé",	
				"15|Russas	",
				"16|Crateús	",
				"17|Tianguá	",
				"18|Aracati	",
				"19|Cascavel	",
				"20|Pacajus 	",
				"21|Icó",
				"22|Horizonte			",	
				"23|Camocim	        ",
				"24|Morada Nova        ",
				"25|Acaraú	",
				"26|Viçosa do Ceará	" ,
				"27|Barbalha	        " ,
				"28|Limoeiro do Norte	" ,
				"29|Tauá	            " ,
				"30|Trairi	            " ,
				"31|Granja	            " ,
				"32|Boa Viagem	        " ,
				"33|Acopiara	        " ,
				"34|Beberibe	        " ,
				"35|Eusébio	        " ,
				"36|Itapajé	        " ,
				"37|Brejo Santo	            ",
				"38|São Gonçalo do Amarante    ",
				"39|São Benedito               ",
				"40|Mauriti	                ",
				"41|Mombaça					",
				"42|Santa Quitéria	",	
				"43|Pedra Branca	",
				"44|Amontada	    ",
				"45|Ipu	        ",
				"46|Itarema	    ",
				"47|Várzea Alegre	",
				"48|Guaraciaba do Norte",
				"49|Itaitinga	",
				"50|Ipueiras	",
				"51|Massapê	",
				"52|Pentecoste	",
				"53|Missão Velha",
				"54|Baturité	",
				"55|Jaguaribe	",
				"56|Ubajara	",
				"57|Paracuru	",
				"58|Jaguaruana	",
				"59|Paraipaba	",
				"60|Bela Cruz	",
				"61|Nova Russa ",
				"62|Santana do Acaraú	  ",
				"63|Lavras da Mangabeira ",
				"64|Parambu	          ",
				"65|Tabuleiro do Norte	  ",
				"66|Milagres	          ",
				"67|Novo Oriente	      ",
				"68|Redenção	          ",
				"69|Campos Sales	      ",
				"70|Jardim	              ",
				"71|Caririaçu	          ",
				"72|Marco	              ",
				"73|Senador Pompeu	 ",
				"74|Aracoiaba	          ",
				"75|Guaiuba	          ",
				"76|Independência	 ",
				"77|Tamboril",
				"78|Ocara	",
				"79|Cedro	",
				"80|Ibiapina",
				"81|Aurora	",
				"82|Jucás	",
				"83|Cruz	",
				"84|Forquilh",
				"85|Irauçuba",
				"86|Assaré	 ",
				"87|Coreaú	 ",
				"88|Barro	 ",
				"89|Morrinho",
				"90|Caridade",
				"91|Quixeré ",
				"92|Uruburetama",
				"93|Araripe		",
				"94|Orós	        ",
				"95|Barreira       ",
				"96|Quiterianópolis",
				"97|Itatira	    ",
				"98|Pindoretama    ",
				"99|Catarina	    ",
				"100|Hidrolândia",	
				"101|Itapiúna   ",
				"102|Madalena   ",
				"103|Umirim	    ",
				"104|Icapuí	    ",
				"105|Jijoca de Jericoacoara    ",
				"106|Chorozinho	     ",
				"107|Reriutaba	     ",
				"108|Cariús	      ",
				"109|Farias Brito     ",
				"110|Tejuçuoca	      ",
				"111|Cariré	       ",
				"112|Varjota	      ",
				"113|Solonópole	      ",
				"114|Jaguaretama     ",
				"115|Banabuiú	      ",
				"116|Croatá	 802      ",
				"117|Capistrano	      ",
				"118|Carnaubal	      ",
				"119|Santana do Cariri	 ",
				"120|Aiuaba	        ",
				"121|Monsenhor Tabosa	 ",
				"122|Alto Santo	    ",
				"123|Piquet Carneiro	 ",
				"124|Acarape	     ",
				"125|Salitre	     ",
				"126|Pereiro	     ",
				"127|Fortim	     ",
				"128|Tururu	     ",
				"129|Saboeiro	     ",
				"130|Nova Olinda     ",
				"131|Graça	          ",
				"132|Porteiras         ",
				"133|Quixelô         ",
				"134|Barroquinha     ",
				"135|Meruoca	     ",
				"136|Apuiarés	     ",
				"137|Mucambo	     ",
				"138|Iracema	     ",
				"139|Frecheirinha    ",
				"140|Uruoca	          ",
				"141|Miraíma         ",
				"142|Choró	          ",
				"143|Ibaretama         ",
				"144|Milhã	          ",
				"145|Palmácia         ",
				"146|Chaval	          ",
				"147|São Luís do Curu	 ",
				"148|Mulungu	     ",
				"149|Ipaumirim	     ",
				"150|Ibicuitinga     ",
				"151|Poranga	     ",
				"152|Pacoti	     ",
				"153|Paramoti	         ",
				"154|Ipaporanga	         ",
				"155|Abaiara	         ",
				"156|Alcântaras	         ",
				"157|Aratuba	          ",
				"158|Jaguaribara	      ",
				"159|Martinópole	      ",
				"160|Groaíras	          ",
				"161|Potengi	          ",
				"162|Ararendá	          ",
				"163|Pires Ferreira	      ",
				"164|Catunda	        ",
				"165|Deputado Irapuan Pinheiro"	,
				"166|Palhano	         ",
				"167|Penaforte	          ",
				"168|Tarrafas	          ",
				"169|Moraújo	         ",
				"170|Jati	              ",
				"171|Arneiroz	         ",
				"172|Itaiçaba	         ",
				"173|São João do Jaguaribe	",
				"174|Umari	             ",
				"175|Senador Sá	        ",
				"176|Altaneira	          ",
				"177|Antonina do Norte ",
				"178|Ererê              ",
				"179|General Sampaio	  ",
				"180|Potiretama	          ",
				"181|Baixio	            ",
				"182|Pacujá             ",
				"183|Granjeiro	         ",
				"184|Guaramiranga  ");
		return municipios;
		
	}

}
