package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosAlagoas {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|  Maceió ",
				"2|  Arapiraca ",
				"3|  Rio Largo ",
				"4|  Palmeira dos Índios ",
				"5|  União dos Palmares ",
				"6|  Penedo ",
				"7|  São Miguel dos Campos ",
				"8|  Coruripe ",
				"9|  Campo Alegre ",
				"10| Delmiro Gouveia ",
				"11| Marechal Deodoro ",
				"12| Santana do Ipanema ",
				"13| Atalaia ",
				"14| Teotônio Vilela ",
				"15| Girau do Ponciano ",
				"16| Pilar ",
				"17| São Luís do Quitunde ",
				"18| São Sebastião ",
				"19| Maragogi ",
				"20| São José da Tapera ",
				"21| Limoeiro de Anadia ",
				"22| Murici ",
				"23| Traipu ",
				"24| Boca da Mata ",
				"25| Porto Calvo ",
				"26| Viçosa ",
				"27| Igaci ",
				"28| Mata Grande ",
				"29| Piranhas ",
				"30| Junqueiro ",
				"31| Matriz de Camaragibe ",
				"32| Pão de Açúcar ",
				"33| Igreja Nova ",
				"34| Craíbas ",
				"35| Joaquim Gomes ",
				"36| São José da Laje ",
				"37| Feira Grande ",
				"38| Colônia Leopoldina ",
				"39| Olho d'Água das Flores ",
				"40| Cajueiro ",
				"41| Água Branca ",
				"42| Porto Real do Colégio ",
				"43| Major Isidoro ",
				"44| Taquarana ",
				"45| Inhapi ",
				"46| Batalha ",
				"47| Estrela de Alagoas ",
				"48| Lagoa da Canoa ",
				"49| Piaçabuçu ",
				"51| Canapi ",
				"52| Anadia ",
				"53| Messias ",
				"54| Capela ",
				"55| Barra de Santo Antônio ",
				"56| Ibateguara ",
				"57| Passo de Camaragibe ",
				"58| Poço das Trincheiras ",
				"59| Senador Rui Palmeira ",
				"60| Satuba ",
				"61| Maribondo ",
				"62| Paripueira ",
				"63| Flexeiras ",
				"64| Novo Lino ",
				"65| Jequiá da Praia ",
				"66| Olivença ",
				"67| Ouro Branco ",
				"68| Quebrangulo ",
				"69| Dois Riachos ",
				"70| Santana do Mundaú ",
				"71| Coité do Noia ",
				"72| Cacimbinhas ",
				"73| Branquinha ",
				"74| Pariconha ",
				"75| Campo Grande ",
				"76| Maravilha ",
				"77| Olho d'Água do Casado ",
				"78| Carneiros ",
				"79| Japaratinga ",
				"80| Barra de São Miguel ",
				"81| Porto de Pedras ",
				"82| São Miguel dos Milagres ",
				"83| Paulo Jacinto ",
				"84| Chã Preta ",
				"85| Santa Luzia do Norte ",
				"86| Monteirópolis ",
				"87| Jacuípe ",
				"88| São Brás ",
				"89| Campestre ",
				"91| Roteiro ",
				"92| Belo Monte ",
				"93| Tanque d'Arca ",
				"94| Coqueiro Seco ",
				"95| Jaramataia ",
				"96| Minador do Negrão ",
				"97| Jacaré dos Homens ",
				"98| Olho d'Água Grande ",
				"99| Palestina ",
				"100|Feliz Deserto ",
				"101|Belém ",
				"102|Jundiá ",
				"103|Mar Vermelho ",
				"104|Pindoba "
		);
		return municipios;
	}
	

}


