package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosBahia {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|  Salvador ",
				"2|  Feira de Santana ",
				"3|  Vitória da Conquista ",
				"4|  Camaçari ",
				"5|  Juazeiro ",
				"6|  Itabuna ",
				"7|  Lauro de Freitas ",
				"8|  Ilhéus ",
				"9|  Jequié ",
				"10| Teixeira de Freitas ",
				"11| Barreiras ",
				"12| Alagoinhas ",
				"13| Porto Seguro ",
				"14| Simões Filho ",
				"15| Paulo Afonso ",
				"16| Eunápolis ",
				"17| Santo Antônio de Jesus ",
				"18| Valença ",
				"19| Candeias ",
				"20| Guanambi ",
				"21| Jacobina ",
				"22| Luís Eduardo Magalhães ",
				"23| Serrinha ",
				"24| Senhor do Bonfim ",
				"25| Dias d'Ávila ",
				"26| Itapetinga ",
				"27| Irecê ",
				"28| Campo Formoso ",
				"29| Casa Nova ",
				"30| Bom Jesus da Lapa ",
				"31| Brumado ",
				"32| Conceição do Coité ",
				"33| Itamaraju ",
				"34| Itaberaba ",
				"35| Cruz das Almas ",
				"36| Ipirá ",
				"37| Santo Amaro ",
				"38| Euclides da Cunha ",
				"39| Catu ",
				"40| Jaguaquara ",
				"41| Araci ",
				"42| Ribeira do Pombal ",
				"43| Barra ",
				"44| Santo Estêvão ",
				"45| Caetité ",
				"46| Tucano ",
				"47| Monte Santo ",
				"48| Macaúbas ",
				"49| Poções ",
				"51| Xique-Xique ",
				"52| Ipiaú ",
				"53| Mata de São João ",
				"54| Livramento de Nossa Senhora ",
				"55| Maragogipe ",
				"56| São Sebastião do Passé ",
				"57| Seabra ",
				"58| Nova Viçosa ",
				"59| Vera Cruz ",
				"60| Entre Rios ",
				"61| Remanso ",
				"62| Mucuri ",
				"63| Sento Sé ",
				"64| Santa Maria da Vitória ",
				"65| Rio Real ",
				"66| Jeremoabo ",
				"67| Inhambupe ",
				"68| São Francisco do Conde ",
				"69| Pojuca ",
				"70| Santaluz ",
				"71| Amargosa ",
				"72| São Gonçalo dos Campos ",
				"73| Esplanada ",
				"74| Itiúba ",
				"75| Morro do Chapéu ",
				"76| Camamu ",
				"77| Riacho de Santana ",
				"78| Itapicuru ",
				"79| Cansanção ",
				"80| Pilão Arcado ",
				"81| Curaçá ",
				"82| Cachoeira ",
				"83| Riachão do Jacuípe ",
				"84| Cícero Dantas ",
				"85| Jaguarari ",
				"86| Barra do Choça ",
				"87| Conceição do Jacuípe ",
				"88| São Desidério ",
				"89| Correntina ",
				"91| Camacan ",
				"92| Gandu ",
				"93| Canavieiras ",
				"94| Serra do Ramalho ",
				"95| Paratinga ",
				"96| Ruy Barbosa ",
				"97| Itabela ",
				"98| Capim Grosso ",
				"99| Muritiba ",
				"100|Carinhanha ",
				"101|Paripiranga ",
				"102|Campo Alegre de Lourdes ",
				"103|Irará ",
				"104|Nazaré ",
				"105|Ituberá ",
				"106|Prado ",
				"107|Olindina ",
				"108|Santa Rita de Cássia ",
				"109|Valente ",
				"110|Quijingue ",
				"111|Santa Cruz Cabrália ",
				"112|Itacaré ",
				"113|Lapão ",
				"114|Presidente Tancredo Neves ",
				"115|Iguaí ",
				"116|Ibotirama ",
				"117|Ubatã ",
				"118|Miguel Calmon ",
				"119|Santana ",
				"120|Mundo Novo ",
				"121|Castro Alves ",
				"122|Planalto ",
				"123|Canarana ",
				"124|Cândido Sales ",
				"125|Queimadas ",
				"126|Amélia Rodrigues ",
				"127|Conde ",
				"128|Formosa do Rio Preto ",
				"129|Iaçu ",
				"130|Uauá ",
				"131|João Dourado ",
				"132|Iraquara ",
				"133|Nova Soure ",
				"134|Piritiba ",
				"135|Itambé ",
				"136|Laje ",
				"137|Ibirapitanga ",
				"138|Belmonte ",
				"139|Coração de Maria ",
				"140|Caculé ",
				"141|Sobradinho ",
				"142|Medeiros Neto ",
				"143|Rafael Jambeiro ",
				"144|Ibicaraí ",
				"145|Teofilândia ",
				"146|Alcobaça ",
				"147|Riachão das Neves ",
				"148|Conceição da Feira ",
				"149|Maracás ",
				"150|Mutuípe ",
				"151|Itaparica ",
				"152|Oliveira dos Brejinhos ",
				"153|Caravelas ",
				"154|Palmas de Monte Alto ",
				"155|Boquira ",
				"156|Wenceslau Guimarães ",
				"157|Paramirim ",
				"158|Guaratinga ",
				"159|Barra da Estiva ",
				"160|São Felipe ",
				"161|Crisópolis ",
				"162|Buritirama ",
				"163|Uruçuca ",
				"164|Itajuípe ",
				"165|Governador Mangabeira ",
				"166|Taperoá ",
				"167|Santa Bárbara ",
				"168|Baixa Grande ",
				"169|Una ",
				"170|Tanhaçu ",
				"171|Maraú ",
				"172|Itororó ",
				"173|Pindobaçu ",
				"174|Madre de Deus ",
				"175|Ubaíra ",
				"176|Itanhém ",
				"177|Ubaitaba ",
				"178|Sátiro Dias ",
				"179|Itarantim ",
				"180|Abaré ",
				"181|Ibicoara ",
				"182|Utinga ",
				"183|Mairi ",
				"184|São Gabriel ",
				"185|Ituaçu ",
				"186|Antas ",
				"187|Anagé ",
				"188|Umburanas ",
				"189|Boa Vista do Tupim ",
				"190|Cocos ",
				"191|Encruzilhada ",
				"192|Cabaceiras do Paraguaçu ",
				"193|Buerarema ",
				"194|Macarani ",
				"195|Jaguaripe ",
				"196|Coaraci ",
				"197|Cafarnaum ",
				"198|Mirangaba ",
				"199|Ibipeba ",
				"200|Fátima ",
				"201|Aporá ",
				"202|Serra Dourada ",
				"203|Piatã ",
				"204|Belo Campo ",
				"205|Conceição do Almeida ",
				"206|Cairu ",
				"207|Pedro Alexandre ",
				"208|Condeúba ",
				"209|Sapeaçu ",
				"210|Ourolândia ",
				"211|Central ",
				"212|Ibititá ",
				"213|Tanque Novo ",
				"214|Tapiramutá ",
				"215|Cipó ",
				"216|Tremedal ",
				"217|Malhada ",
				"218|Água Fria ",
				"219|Souto Soares ",
				"220|Urandi ",
				"221|Adustina ",
				"222|Canudos ",
				"223|Ibirataia ",
				"224|Filadélfia ",
				"225|Nova Canaã ",
				"226|Bonito ",
				"227|Pindaí ",
				"228|Ibitiara ",
				"229|Coronel João Sá ",
				"230|América Dourada ",
				"231|Ibicuí ",
				"232|Biritinga ",
				"233|Itaeté ",
				"234|Barrocas ",
				"235|Igaporã ",
				"236|Caetanos ",
				"237|Novo Triunfo ",
				"238|Serra Preta ",
				"239|Lagoa Real ",
				"240|Jussara ",
				"241|Glória ",
				"242|Ponto Novo ",
				"243|São Félix do Coribe ",
				"244|Rio do Antônio ",
				"245|Salinas da Margarida ",
				"246|Presidente Dutra ",
				"247|Acajutiba ",
				"248|Itagibá ",
				"249|Ipecaetá ",
				"250|Andorinha ",
				"251|Jacaraci ",
				"252|Ribeira do Amparo ",
				"253|Ibipitanga ",
				"254|Teolândia ",
				"255|São Félix ",
				"256|Barro Alto ",
				"257|Brejões ",
				"258|Jiquiriçá ",
				"259|Santa Brígida ",
				"260|Itatim ",
				"270|Coribe ",
				"271|Candiba ",
				"272|Boninal ",
				"273|Retirolândia ",
				"274|Mascote ",
				"275|Itaguaçu da Bahia ",
				"276|Angical ",
				"277|Várzea da Roça ",
				"278|Barra do Mendes ",
				"279|Uibaí ",
				"280|Cotegipe ",
				"281|Cristópolis ",
				"282|Nilo Peçanha ",
				"283|Baianópolis ",
				"284|Manoel Vitorino ",
				"285|Pé de Serra ",
				"286|Igrapiúna ",
				"287|Boa Nova ",
				"288|Aracatu ",
				"289|Mansidão ",
				"290|Serrolândia ",
				"291|Banzaê ",
				"292|Andaraí ",
				"293|Heliópolis ",
				"294|Caldeirão Grande ",
				"295|Rio de Contas ",
				"296|Nordestina ",
				"297|Terra Nova ",
				"298|Várzea Nova ",
				"299|Sítio do Mato ",
				"300|Santa Luzia ",
				"301|Saúde ",
				"302|Presidente Jânio Quadros ",
				"303|Itiruçu ",
				"304|Itagi ",
				"305|Tabocas do Brejo Velho ",
				"306|Licínio de Almeida ",
				"307|Wanderley ",
				"308|Aurelino Leal ",
				"309|Jitaúna ",
				"310|Araças ",
				"311|Dom Basílio ",
				"312|Mortugaba ",
				"313|Novo Horizonte ",
				"314|Matina ",
				"315|Saubara ",
				"316|Antônio Cardoso ",
				"317|Capela do Alto Alegre ",
				"318|Rio do Pires ",
				"319|São Miguel das Matas ",
				"320|Antônio Gonçalves ",
				"321|Mulungu do Morro ",
				"322|Macajuba ",
				"323|Piripá ",
				"324|Dário Meira ",
				"325|Aramari ",
				"326|Sebastião Laranjeiras ",
				"327|Arataca ",
				"328|Muquém de São Francisco ",
				"329|Gentio do Ouro ",
				"330|Lençóis ",
				"331|Chorrochó ",
				"332|Milagres ",
				"333|Anguera ",
				"334|Iuiú ",
				"335|Sítio do Quinto ",
				"336|Floresta Azul ",
				"337|Érico Cardoso ",
				"338|Santa Inês ",
				"339|Jandaíra ",
				"400|Pintadas ",
				"401|Brotas de Macaúbas ",
				"402|Marcionílio Souza ",
				"403|Botuporã ",
				"404|Brejolândia ",
				"405|Itapebi ",
				"406|Itapitanga ",
				"407|São José do Jacuípe ",
				"408|Santa Teresinha ",
				"409|Pau Brasil ",
				"410|Bom Jesus da Serra ",
				"411|Piraí do Norte ",
				"412|Maiquinique ",
				"413|Ibiassucê ",
				"414|Ipupiara ",
				"415|Canápolis ",
				"416|Caém ",
				"417|Mucugê ",
				"418|Jucuruçu ",
				"419|Iramaia ",
				"420|Itapé ",
				"421|Caraíbas ",
				"422|Caturama ",
				"423|Wagne           ",
				"424|Planaltino                    ",
				"425|Mirante               ",
				"426|Cardeal da Silva             ",
				"427|Nova Redenção                 ",
				"428|Várzea do Poço                      ",
				"429|Quixabeira                 ",
				"430|Rodelas                   ",
				"431|São Domingos                      ",
				"432|Varzedo                        ",
				"433|Santanópolis                ",
				"434|Palmeiras                       ",
				"435|Abaíra                      ",
				"436|Aratuípe            ",
				"437|Jaborandi               ",
				"438|Lamarão                ",
				"439|Morpará                      ",
				"440|Ouriçangas                          ",
				"441|Cordeiros                   ",
				"442|Lajedo do Tabocal                    ",
				"443|Malhada de Pedras           ",
				"444|Ibirapuã                 ",
				"445|Candeal                  ",
				"446|Itaquara                    ",
				"447|Itamari              ",
				"448|Elísio Medrado             ",
				"449|Potiraguá                 ",
				"500|Nova Itarana                    ",
				"501|Macururé                       ",
				"502|Tanquinho                ",
				"503|Nova Fátima                    ",
				"504|Guajeru                        ",
				"505|Teodoro Sampaio                          ",
				"506|Gongogi                        ",
				"507|Caatiba                     ",
				"508|Apuarema                        ",
				"509|Muniz Ferreira                       ",
				"510|Pedrão                       ",
				"511|Irajuba                         ",
				"512|Ribeirão do Largo                ",
				"513|Itagimirim                   ",
				"514|Itaju do Colônia                      ",
				"515|Jussiape                     ",
				"516|Nova Ibiá                      ",
				"517|Itanagra                       ",
				"518|Santa Cruz da Vitória                      ",
				"519|Vereda          ",
				"520|Ichu               ",
				"521|Jussari                     ",
				"522|Barra do Rocha                       ",
				"523|Barro Preto             ",
				"524|São José da Vitória                     ",
				"525|Almadina                        ",
				"526|Feira da Mata                  ",
				"527|Firmino Alves                       ",
				"528|Cravolândia                        ",
				"529|Aiquara                       ",
				"530|Gavião                   ",
				"531|Maetinga                          ",
				"532|Contendas do Sincorá             ",
				"533|Ibiquera                       ",
				"534|Dom Macedo Costa                   ",
				"535|Lajedão                     ",
				"536|Lajedinho                  ",
				"537|Lafaiete Coutinho                    ",
				"538|Catolândia                      "
				
				
		);
		return municipios;
	}
	

}


