package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;

public class JobCadMunicipiosMaranhao {
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(
				"1|Açailândia                       ",
				"2|Afonso Cunha                     ",
				"3|Água Doce do Maranhão            ",
				"4|Alcântara                        ",
				"5|Aldeias Altas                    ",
				"6|Altamira do Maranhão             ",
				"7|Alto Alegre do Maranhão          ",
				"8|Alto Alegre do Pindaré           ",
				"9|Alto Parnaíba                    ",
				"10|Amapá do Maranhão                ",
				"11|Amarante do Maranhão             ",
				"12|Anajatuba                        ",
				"13|Anapurus                         ",
				"14|Apicum-Açu                       ",
				"15|Araguanã                         ",
				"16|Araioses                         ",
				"17|Arame                            ",
				"18|Arari                            ",
				"19|Axixá                            ",
				"20|Bacabal                          ",
				"21|Bacabeira                        ",
				"22|Bacuri                           ",
				"23|Bacurituba                       ",
				"24|Balsas                           ",
				"25|Barão de Grajaú                  ",
				"26|Barra do Corda                   ",
				"27|Barreirinhas                     ",
				"28|Bela Vista do Maranhão           ",
				"29|Belágua                          ",
				"30|Benedito Leite                   ",
				"31|Bequimão                         ",
				"32|Bernardo do Mearim               ",
				"33|Boa Vista do Gurupi              ",
				"34|Bom Jardim                       ",
				"35|Bom Jesus das Selvas             ",
				"36|Bom Lugar                        ",
				"37|Brejo                            ",
				"38|Brejo de Areia                   ",
				"39|Buriti                           ",
				"40|Buriti Bravo                     ",
				"41|Buriticupu                       ",
				"42|Buritirana                       ",
				"43|Cachoeira Grande                 ",
				"44|Cajapió                          ",
				"45|Cajari                           ",
				"46|Campestre do Maranhão            ",
				"47|Cândido Mendes                   ",
				"48|Cantanhede                       ",
				"49|Capinzal do Norte                ",
				"50|Carolina                         ",
				"51|Carutapera                       ",
				"52|Caxias                           ",
				"53|Cedral                           ",
				"54|Central do Maranhão              ",
				"55|Centro do Guilherme              ",
				"56|Centro Novo do Maranhão          ",
				"57|Chapadinha                       ",
				"58|Cidelândia                       ",
				"59|Codó                             ",
				"60|Coelho Neto                      ",
				"61|Colinas                          ",
				"62|Conceição do Lago-Açu            ",
				"63|Coroatá                          ",
				"64|Cururupu                         ",
				"65|Davinópolis                      ",
				"66|Dom Pedro                        ",
				"67|Duque Bacelar                    ",
				"68|Esperantinópolis                 ",
				"69|Estreito                         ",
				"70|Feira Nova do Maranhão           ",
				"71|Fernando Falcão                  ",
				"72|Formosa da Serra Negra           ",
				"73|Fortaleza dos Nogueiras          ",
				"74|Fortuna                          ",
				"75|Godofredo Viana                  ",
				"76|Gonçalves Dias                   ",
				"77|Governador Archer                ",
				"78|Governador Edison Lobão          ",
				"79|Governador Eugênio Barros        ",
				"80|Governador Luiz Rocha            ",
				"81|Governador Newton Bello          ",
				"82|Governador Nunes Freire          ",
				"83|Graça Aranha                     ",
				"84|Grajaú                           ",
				"85|Guimarães                        ",
				"86|Humberto de Campos               ",
				"87|Icatu                            ",
				"88|Igarapé do Meio                  ",
				"89|Igarapé Grande                   ",
				"90|Imperatriz                       ",
				"91|Itaipava do Grajaú               ",
				"92|Itapecuru Mirim                  ",
				"93|Itinga do Maranhão               ",
				"94|Jatobá                           ",
				"95|Jenipapo dos Vieiras             ",
				"96|João Lisboa                      ",
				"97|Joselândia                       ",
				"98|Junco do Maranhão                ",
				"99|Lago da Pedra                    ",
				"100|Lago do Junco                    ",
				"101|Lago dos Rodrigues               ",
				"102|Lago Verde                       ",
				"103|Lagoa do Mato                    ",
				"104|Lagoa Grande do Maranhão         ",
				"105|Lajeado Novo                     ",
				"106|Lima Campos                      ",
				"107|Loreto                           ",
				"108|Luís Domingues                   ",
				"109|Magalhães de Almeida             ",
				"110|Maracaçumé                       ",
				"111|Marajá do Sena                   ",
				"112|Maranhãozinho                    ",
				"113|Mata Roma                        ",
				"114|Matinha                          ",
				"115|Matões                           ",
				"116|Matões do Norte                  ",
				"117|Milagres do Maranhão             ",
				"118|Mirador                          ",
				"119|Miranda do Norte                 ",
				"120|Mirinzal                         ",
				"121|Monção                           ",
				"122|Montes Altos                     ",
				"123|Morros                           ",
				"124|Nina Rodrigues                   ",
				"125|Nova Colinas                     ",
				"126|Nova Iorque                      ",
				"127|Nova Olinda do Maranhão          ",
				"128|Olho d`Água das Cunhãs           ",
				"129|Olinda Nova do Maranhão          ",
				"130|Paço do Lumiar                   ",
				"131|Palmeirândia                     ",
				"132|Paraibano                        ",
				"133|Parnarama                        ",
				"134|Passagem Franca                  ",
				"135|Pastos Bons                      ",
				"136|Paulino Neves                    ",
				"137|Paulo Ramos                      ",
				"138|Pedreiras                        ",
				"139|Pedro do Rosário                 ",
				"140|Penalva                          ",
				"141|Peri Mirim                       ",
				"142|Peritoró                         ",
				"143|Pindaré-Mirim                    ",
				"144|Pinheiro                         ",
				"145|Pio XII                          ",
				"146|Pirapemas                        ",
				"147|Poção de Pedras                  ",
				"148|Porto Franco                     ",
				"149|Porto Rico do Maranhão           ",
				"150|Presidente Dutra                 ",
				"151|Presidente Juscelino             ",
				"152|Presidente Médici                ",
				"153|Presidente Sarney                ",
				"154|Presidente Vargas                ",
				"155|Primeira Cruz                    ",
				"156|Raposa                           ",
				"157|Riachão                          ",
				"158|Ribamar Fiquene                  ",
				"159|Rosário                          ",
				"160|Sambaíba                         ",
				"161|Santa Filomena do Maranhão       ",
				"162|Santa Helena                     ",
				"163|Santa Inês                       ",
				"164|Santa Luzia                      ",
				"165|Santa Luzia do Paruá             ",
				"166|Santa Quitéria do Maranhão       ",
				"167|Santa Rita                       ",
				"168|Santana do Maranhão              ",
				"169|Santo Amaro do Maranhão          ",
				"170|Santo Antônio dos Lopes          ",
				"171|São Benedito do Rio Preto        ",
				"172|São Bento                        ",
				"173|São Bernardo                     ",
				"174|São Domingos do Azeitão          ",
				"175|São Domingos do Maranhão         ",
				"176|São Félix de Balsas              ",
				"177|São Francisco do Brejão          ",
				"178|São Francisco do Maranhão        ",
				"179|São João Batista                 ",
				"180|São João do Carú                 ",
				"181|São João do Paraíso              ",
				"182|São João do Soter                ",
				"183|São João dos Patos               ",
				"184|São José de Ribamar              ",
				"185|São José dos Basílios            ",
				"186|São Luís                         ",
				"187|São Luís Gonzaga do Maranhão     ",
				"188|São Mateus do Maranhão           ",
				"189|São Pedro da Água Branca         ",
				"190|São Pedro dos Crentes            ",
				"191|São Raimundo das Mangabeiras     ",
				"192|São Raimundo do Doca Bezerra     ",
				"193|São Roberto                      ",
				"194|São Vicente Ferrer               ",
				"195|Satubinha                        ",
				"196|Senador Alexandre Costa          ",
				"197|Senador La Rocque                ",
				"198|Serrano do Maranhão              ",
				"199|Sítio Novo                       ",
				"200|Sucupira do Norte                ",
				"201|Sucupira do Riachão              ",
				"202|Tasso Fragoso                    ",
				"203|Timbiras                         ",
				"204|Timon                            ",
				"205|Trizidela do Vale                ",
				"206|Tufilândia                       ",
				"207|Tuntum                           ",
				"208|Turiaçu                          ",
				"209|Turilândia                       ",
				"210|Tutóia                           ",
				"211|Urbano Santos                    ",
				"212|Vargem Grande                    ",
				"213|Viana                            ",
				"214|Vila Nova dos Martírios          ",
				"215|Vitória do Mearim                ",
				"216|Vitorino Freire                  "

		);
		return municipios;
	}

}
