package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosRioGrandeDoNorte {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|  Natal",
				"2|  Mossoró",
				"3|  Parnamirim",
				"4|  São Gonçalo do Amarante",
				"5|  Macaíba",
				"6|  Ceará-Mirim",
				"7|  Caicó",
				"8|  Assu",
				"9|  Currais Novos",
				"10| São José de Mipibu",
				"11| Santa Cruz",
				"12| Nova Cruz",
				"13| Apodi",
				"14| João Câmara",
				"15| Touros",
				"16| Canguaretama",
				"17| Macau",
				"18| Pau dos Ferros",
				"19| Areia Branca",
				"20| Extremoz",
				"21| Baraúna",
				"22| Nísia Floresta",
				"23| Goianinha",
				"24| Santo Antônio",
				"25| São Miguel",
				"26| Monte Alegre",
				"27| Parelhas",
				"28| Caraúbas",
				"29| Jucurutu",
				"30| São Paulo do Potengi",
				"31| Tangará",
				"32| Pedro Velho",
				"33| Lagoa Nova",
				"34| Poço Branco",
				"35| Ipanguaçu",
				"36| Santana do Matos",
				"37| Jardim de Piranhas",
				"38| Alexandria",
				"39| Pendências",
				"40| Upanema",
				"41| Arez",
				"42| Guamaré",
				"43| Governador Dix-Sept Rosado",
				"44| São José do Campestre",
				"45| Alto do Rodrigues",
				"46| Ielmo Marinho",
				"47| Jardim do Seridó",
				"48| Patu",
				"49| Taipu",
				"51| Brejinho",
				"52| Angicos",
				"53| Montanhas",
				"54| Tibau do Sul",
				"55| Passa-e-Fica",
				"56| Acari",
				"57| Cerro Corá",
				"58| Afonso Bezerra",
				"59| São Tomé",
				"60| Vera Cruz",
				"61| Umarizal",
				"62| Espírito Santo",
				"63| Maxaranguape",
				"64| Lajes",
				"65| Serra do Mel",
				"66| Campo Redondo",
				"67| Rio do Fogo",
				"68| Tenente Ananias",
				"69| Carnaubais",
				"70| Luís Gomes",
				"71| Bom Jesus",
				"72| Grossos",
				"73| Campo Grande",
				"74| Boa Saúde",
				"75| Florânia",
				"76| Serra Caiada",
				"77| São Miguel do Gostoso",
				"78| Baía Formosa",
				"79| Pureza",
				"80| Marcelino Vieira",
				"81| Martins",
				"82| São Rafael",
				"83| Cruzeta",
				"84| Jaçanã",
				"85| Serra Negra do Norte",
				"86| Lagoa Salgada",
				"87| Carnaúba dos Dantas",
				"88| Portalegre",
				"89| Pedro Avelino",
				"91| Riachuelo",
				"92| Lagoa de Pedras",
				"93| Itajá",
				"94| Antônio Martins",
				"95| Jandaíra",
				"96| Serrinha",
				"97| Doutor Severiano",
				"98| Lagoa d'Anta",
				"99| São Pedro",
				"100|São Vicente",
				"101|Caiçara do Norte",
				"102|São João do Sabugi",
				"103|José da Penha",
				"104|Equador",
				"105|Severiano Melo",
				"106|Serra de São Bento",
				"107|Felipe Guerra",
				"108|Senador Elói de Souza",
				"109|Itaú",
				"110|Japi",
				"111|Tenente Laurentino Cruz",
				"112|Coronel Ezequiel",
				"113|Janduís",
				"114|Encanto",
				"115|Várzea",
				"116|Porto do Mangue",
				"117|Bento Fernandes",
				"118|Sítio Novo",
				"119|Almino Afonso",
				"120|Parazinho",
				"121|Coronel João Pessoa",
				"122|Santa Maria",
				"123|Ouro Branco",
				"124|Rafael Fernandes",
				"125|Lajes Pintadas",
				"126|Serrinha dos Pintos",
				"127|Rodolfo Fernandes",
				"128|Olho-d'Água do Borges",
				"129|Frutuoso Gomes",
				"130|São José do Seridó",
				"131|Messias Targino",
				"132|Riacho de Santana",
				"133|Barcelona",
				"134|Paraná",
				"135|Senador Georgino Avelino",
				"136|São Bento do Trairi",
				"137|São Francisco do Oeste",
				"138|Paraú",
				"139|Venha-Ver",
				"140|Tibau",
				"141|Lucrécia",
				"142|Ruy Barbosa",
				"143|Jundiá",
				"144|Major Sales",
				"145|Pedra Grande",
				"146|Pilões",
				"147|São Fernando",
				"148|Triunfo Potiguar",
				"149|Caiçara do Rio do Vento",
				"150|Riacho da Cruz",
				"151|Rafael Godeiro",
				"152|Água Nova",
				"153|São Bento do Norte",
				"154|Passagem",
				"155|Francisco Dantas",
				"156|Vila Flor",
				"157|Fernando Pedroza",
				"158|Lagoa de Velhos",
				"159|Jardim de Angicos",
				"160|João Dias",
				"161|Pedra Preta",
				"162|Santana do Seridó",
				"163|Bodó",
				"164|Taboleiro Grande",
				"165|Timbaúba dos Batistas",
				"166|Monte das Gameleiras",
				"167|Galinhos",
				"168|Ipueira",
				"169|Viçosa"
		);
		return municipios;
	}
	

}


