package br.com.petshow.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosTocantins {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|  Palmas",
				"2|  Araguaína",
				"3|  Gurupi",
				"4|  Porto Nacional",
				"5|  Paraíso do Tocantins",
				"6|  Araguatins",
				"7|  Colinas do Tocantins",
				"8|  Guaraí",
				"9|  Tocantinópolis",
				"10| Dianópolis",
				"11| Miracema do Tocantins",
				"12| Formoso do Araguaia",
				"13| Augustinópolis",
				"14| Taguatinga",
				"15| Miranorte",
				"16| Pedro Afonso",
				"17| Goiatins",
				"18| Lagoa da Confusão",
				"19| São Miguel do Tocantins",
				"20| Xambioá",
				"21| Wanderlândia",
				"22| Nova Olinda",
				"23| Peixe",
				"24| Buriti do Tocantins",
				"25| Arraias",
				"26| Babaçulândia",
				"27| Paranã",
				"28| Esperantina",
				"29| Ananás",
				"30| Axixá do Tocantins",
				"31| Campos Lindos",
				"32| Natividade",
				"33| Sítio Novo do Tocantins",
				"34| Filadélfia",
				"35| Araguaçu",
				"36| Alvorada",
				"37| Colméia",
				"38| Praia Norte",
				"39| Ponte Alta do Tocantins",
				"40| Palmeirópolis",
				"41| Monte do Carmo",
				"42| Itacajá",
				"43| Almas",
				"44| Cristalândia",
				"45| Pium",
				"46| Tocantínia",
				"47| Dois Irmãos do Tocantins",
				"48| Santa Fé do Araguaia",
				"49| Araguacema",
				"51| Arapoema",
				"52| Divinópolis do Tocantins",
				"53| Rio Sono",
				"54| Palmeiras do Tocantins",
				"55| Aguiarnópolis",
				"56| Itaguatins",
				"57| Aragominas",
				"58| Darcinópolis",
				"59| Palmeirante",
				"60| Aliança do Tocantins",
				"61| Barrolândia",
				"62| Araguanã",
				"63| Figueirópolis",
				"64| Brejinho de Nazaré",
				"65| Couto de Magalhães",
				"66| Pequizeiro",
				"67| Silvanópolis",
				"68| Goianorte",
				"69| Caseara",
				"70| São Bento do Tocantins",
				"71| Marianópolis do Tocantins",
				"72| Combinado",
				"73| Pau-d'Arco",
				"74| Santa Rosa do Tocantins",
				"75| Dueré",
				"76| São Sebastião do Tocantins",
				"77| Ponte Alta do Bom Jesus",
				"78| Aparecida do Rio Negro",
				"79| Pindorama do Tocantins",
				"80| Bernardo Sayão",
				"81| Riachinho",
				"82| Bom Jesus do Tocantins",
				"83| Barra do Ouro",
				"84| Sampaio",
				"85| São Valério da Natividade",
				"86| Conceição do Tocantins",
				"87| Cariri do Tocantins",
				"88| Nazaré",
				"89| Recursolândia",
				"91| Novo Acordo",
				"92| Nova Rosalândia",
				"93| Lagoa do Tocantins",
				"94| Carrasco Bonito",
				"95| Fátima",
				"96| Lizarda",
				"97| Jaú do Tocantins",
				"98| Presidente Kennedy",
				"99| Itapiratins",
				"100|Aurora do Tocantins",
				"101|Muricilândia",
				"102|Bandeirantes do Tocantins",
				"103|Sandolândia",
				"104|Angico",
				"105|Chapada da Natividade",
				"106|Maurilândia do Tocantins",
				"107|Santa Maria do Tocantins",
				"108|São Salvador do Tocantins",
				"109|Porto Alegre do Tocantins",
				"110|Piraquê",
				"111|Lajeado",
				"112|Luzinópolis",
				"113|Centenário",
				"114|Rio dos Bois",
				"115|Santa Tereza do Tocantins",
				"116|Talismã",
				"117|Novo Jardim",
				"118|Pugmil",
				"119|Fortaleza do Tabocão",
				"120|Santa Terezinha do Tocantins",
				"121|Abreulândia",
				"122|Mateiros",
				"123|Carmolândia",
				"124|Itaporã do Tocantins",
				"125|Tupiratins",
				"126|Novo Alegre",
				"127|Santa Rita do Tocantins",
				"128|Cachoeirinha",
				"129|Juarina",
				"130|Monte Santo do Tocantins",
				"131|Brasilândia do Tocantins",
				"132|Taipas do Tocantins",
				"133|Rio da Conceição",
				"134|Sucupira",
				"135|Ipueiras",
				"136|Lavandeira",
				"137|Tupirama",
				"138|Crixás do Tocantins",
				"139|São Félix do Tocantins",
				"140|Chapada de Areia",
				"141|Oliveira de Fátima"
				
		);
		return municipios;
	}
	

}


