package br.com.petmooby.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosSaoPaulo {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|Adamantina                      ",
				"2|Adolfo                          ",
				"3|Aguai                           ",
				"4|Aguas da Prata                  ",
				"5|Aguas de Lindoia                ",
				"6|Aguas de Santa Barbara          ",
				"7|Aguas de Sao Pedro              ",
				"8|Agudos                          ",
				"9|Alambari                        ",
				"10|Alfredo Marcondes               ",
				"11|Altair                          ",
				"12|Altinopolis                     ",
				"13|Alto Alegre                     ",
				"14|Aluminio                        ",
				"15|Alvares Florence                ",
				"16|Alvares Machado                 ",
				"17|Alvaro de Carvalho              ",
				"18|Alvinlandia                     ",
				"19|Americana                       ",
				"20|Americo Brasiliense             ",
				"21|Americo de Campos               ",
				"22|Amparo                          ",
				"23|Analandia                       ",
				"24|Andradina                       ",
				"25|Angatuba                        ",
				"26|Anhembi                         ",
				"27|Anhumas                         ",
				"28|Aparecida d'Oeste               ",
				"29|Aparecida                       ",
				"30|Apiai                           ",
				"31|Aracariguama                    ",
				"32|Aracatuba                       ",
				"33|Aracoiaba da Serra              ",
				"34|Aramina                         ",
				"35|Arandu                          ",
				"36|Arapei                          ",
				"37|Araraquara                      ",
				"38|Araras                          ",
				"39|Arco-Iris                       ",
				"40|Arealva                         ",
				"41|Areias                          ",
				"42|Areiopolis                      ",
				"43|Ariranha                        ",
				"44|Artur Nogueira                  ",
				"45|Aruja                           ",
				"46|Aspasia                         ",
				"47|Assis                           ",
				"48|Atibaia                         ",
				"49|Auriflama                       ",
				"51|Avai                            ",
				"52|Avanhandava                     ",
				"53|Avare                           ",
				"54|Bady Bassitt                    ",
				"55|Balbinos                        ",
				"56|Balsamo                         ",
				"57|Bananal                         ",
				"58|Barao de Antonina               ",
				"59|Barbosa                         ",
				"60|Bariri                          ",
				"61|Barra Bonita                    ",
				"62|Barra do Chapeu                 ",
				"63|Barra do Turvo                  ",
				"64|Barretos                        ",
				"65|Barrinha                        ",
				"66|Barueri                         ",
				"67|Bastos                          ",
				"68|Batatais                        ",
				"69|Bauru                           ",
				"70|Bebedouro                       ",
				"71|Bento de Abreu                  ",
				"72|Bernardino de Campos            ",
				"73|Bertioga                        ",
				"74|Bilac                           ",
				"75|Birigui                         ",
				"76|Biritiba-Mirim                  ",
				"77|Boa Esperanca do Sul            ",
				"78|Bocaina                         ",
				"79|Bofete                          ",
				"80|Boituva                         ",
				"81|Bom Jesus dos Perdoes           ",
				"82|Bom Sucesso de Itarare          ",
				"83|Bora                            ",
				"84|Boraceia                        ",
				"85|Borborema                       ",
				"86|Borebi                          ",
				"87|Botucatu                        ",
				"88|Braganca Paulista               ",
				"89|Brauna                          ",
				"91|Brejo Alegre                    ",
				"92|Brodosqui                       ",
				"93|Brotas                          ",
				"94|Buri                            ",
				"95|Buritama                        ",
				"96|Buritizal                       ",
				"97|Cabralia Paulista               ",
				"98|Cabreuva                        ",
				"99|Cacapava                        ",
				"100|Cachoeira Paulista              ",
				"101|Caconde                         ",
				"102|Cafelandia                      ",
				"103|Caiabu                          ",
				"104|Caieiras                        ",
				"105|Caiua                           ",
				"106|Cajamar                         ",
				"107|Cajati                          ",
				"108|Cajobi                          ",
				"109|Cajuru                          ",
				"110|Campina do Monte Alegre         ",
				"111|Campinas                        ",
				"112|Campo Limpo Paulista            ",
				"113|Campos Novos Paulista           ",
				"114|Campos do Jordao                ",
				"115|Cananeia                        ",
				"116|Canas                           ",
				"117|Candido Mota                    ",
				"118|Candido Rodrigues               ",
				"119|Canitar                         ",
				"120|Capao Bonito                    ",
				"121|Capela do Alto                  ",
				"122|Capivari                        ",
				"123|Caraguatatuba                   ",
				"124|Carapicuiba                     ",
				"125|Cardoso                         ",
				"126|Casa Branca                     ",
				"127|Cassia dos Coqueiros            ",
				"128|Castilho                        ",
				"129|Catanduva                       ",
				"130|Catigua                         ",
				"131|Cedral                          ",
				"132|Cerqueira Cesar                 ",
				"133|Cerquilho                       ",
				"134|Cesario Lange                   ",
				"135|Charqueada                      ",
				"136|Chavantes                       ",
				"137|Clementina                      ",
				"138|Colina                          ",
				"139|Colombia                        ",
				"140|Conchal                         ",
				"141|Conchas                         ",
				"142|Cordeiropolis                   ",
				"143|Coroados                        ",
				"144|Coronel Macedo                  ",
				"145|Corumbatai                      ",
				"146|Cosmopolis                      ",
				"147|Cosmorama                       ",
				"148|Cotia                           ",
				"149|Cravinhos                       ",
				"150|Cristais Paulista               ",
				"151|Cruzalia                        ",
				"152|Cruzeiro                        ",
				"153|Cubatao                         ",
				"154|Cunha                           ",
				"155|Descalvado                      ",
				"156|Diadema                         ",
				"157|Dirce Reis                      ",
				"158|Divinolandia                    ",
				"159|Dobrada                         ",
				"160|Dois Corregos                   ",
				"161|Dolcinopolis                    ",
				"162|Dourado                         ",
				"163|Dracena                         ",
				"164|Duartina                        ",
				"165|Dumont                          ",
				"166|Echapora                        ",
				"167|Eldorado                        ",
				"168|Elias Fausto                    ",
				"169|Elisiario                       ",
				"170|Embauba                         ",
				"171|Embu                            ",
				"172|Embu-Guacu                      ",
				"173|Emilianopolis                   ",
				"174|Engenheiro Coelho               ",
				"175|Espirito Santo do Pinhal        ",
				"176|Espirito Santo do Turvo         ",
				"177|Estiva Gerbi                    ",
				"178|Estrela d'Oeste                 ",
				"179|Estrela do Norte                ",
				"180|Euclides da Cunha Paulista      ",
				"181|Fartura                         ",
				"182|Fernando Prestes                ",
				"183|Fernandopolis                   ",
				"184|Fernao                          ",
				"185|Ferraz de Vasconcelos           ",
				"186|Flora Rica                      ",
				"187|Floreal                         ",
				"188|Florida Paulista                ",
				"189|Florinia                        ",
				"190|Franca                          ",
				"191|Francisco Morato                ",
				"192|Franco da Rocha                 ",
				"193|Gabriel Monteiro                ",
				"194|Galia                           ",
				"195|Garca                           ",
				"196|Gastao Vidigal                  ",
				"197|Gaviao Peixoto                  ",
				"198|General Salgado                 ",
				"199|Getulina                        ",
				"200|Glicerio                        ",
				"201|Guaicara                        ",
				"202|Guaimbe                         ",
				"203|Guaira                          ",
				"204|Guapiacu                        ",
				"205|Guapiara                        ",
				"206|Guara							 ",
				"207|Guaracai                        ",
				"208|Guaraci                         ",
				"209|Guarani d'Oeste                 ",
				"210|Guaranta                        ",
				"211|Guararapes                      ",
				"212|Guararema                       ",
				"213|Guaratingueta                   ",
				"214|Guarei                          ",
				"215|Guariba                         ",
				"216|Guaruja                         ",
				"217|Guarulhos                       ",
				"218|Guatapara                       ",
				"219|Guzolandia                      ",
				"220|Herculandia                     ",
				"221|Holambra                        ",
				"222|Hortolandia                     ",
				"223|Iacanga                         ",
				"224|Iacri                           ",
				"225|Iaras                           ",
				"226|Ibate                           ",
				"227|Ibira                           ",
				"228|Ibirarema                       ",
				"229|Ibitinga                        ",
				"230|Ibiuna                          ",
				"231|Icem                            ",
				"232|Iepe                            ",
				"233|Igaracu do Tiete                ",
				"234|Igarapava                       ",
				"235|Igarata                         ",
				"236|Iguape                          ",
				"237|Ilha Comprida                   ",
				"238|Ilha Solteira                   ",
				"239|Ilhabela                        ",
				"240|Indaiatuba                      ",
				"241|Indiana                         ",
				"242|Indiapora                       ",
				"243|Inubia Paulista                 ",
				"244|Ipaucu                          ",
				"245|Ipero                           ",
				"246|Ipeuna                          ",
				"247|Ipigua                          ",
				"248|Iporanga                        ",
				"249|Ipua                            ",
				"250|Iracemapolis                    ",
				"251|Irapua                          ",
				"252|Irapuru                         ",
				"253|Itabera                         ",
				"254|Itai                            ",
				"255|Itajobi                         ",
				"256|Itaju                           ",
				"257|Itanhaem                        ",
				"258|Itaoca                          ",
				"259|Itapecerica da Serra            ",
				"260|Itapetininga                    ",
				"270|Itapeva                         ",
				"271|Itapevi                         ",
				"272|Itapira                         ",
				"273|Itapirapua Paulista             ",
				"274|Itapolis                        ",
				"275|Itaporanga                      ",
				"276|Itapui                          ",
				"277|Itapura                         ",
				"278|Itaquaquecetuba                 ",
				"279|Itarare                         ",
				"280|Itariri                         ",
				"281|Itatiba                         ",
				"282|Itatinga                        ",
				"283|Itirapina                       ",
				"284|Itirapua                        ",
				"285|Itobi                           ",
				"286|Itu                             ",
				"287|Itupeva                         ",
				"288|Ituverava                       ",
				"289|Jaborandi                       ",
				"290|Jaboticabal                     ",
				"291|Jacarei                         ",
				"292|Jaci                            ",
				"293|Jacupiranga                     ",
				"294|Jaguariuna                      ",
				"295|Jales                           ",
				"296|Jambeiro                        ",
				"297|Jandira                         ",
				"298|Jardinopolis                    ",
				"299|Jarinu                          ",
				"300|Jau                             ",
				"301|Jeriquara                       ",
				"302|Joanopolis                      ",
				"303|Joao Ramalho                    ",
				"304|Jose Bonifacio                  ",
				"305|Julio Mesquita                  ",
				"306|Jumirim                         ",
				"307|Jundiai                         ",
				"308|Junqueiropolis                  ",
				"309|Juquia                          ",
				"310|Juquitiba                       ",
				"311|Lagoinha                        ",
				"312|Laranjal Paulista               ",
				"313|Lavinia                         ",
				"314|Lavrinhas                       ",
				"315|Leme                            ",
				"316|Lencois Paulista                ",
				"317|Limeira                         ",
				"318|Lindoia                         ",
				"319|Lins                            ",
				"320|Lorena                          ",
				"321|Lourdes                         ",
				"322|Louveira                        ",
				"323|Lucelia                         ",
				"324|Lucianopolis                    ",
				"325|Luis Antonio                    ",
				"326|Luiziania                       ",
				"327|Lupercio                        ",
				"328|Lutecia                         ",
				"329|Macatuba                        ",
				"330|Macaubal                        ",
				"331|Macedonia                       ",
				"332|Magda                           ",
				"333|Mairinque                       ",
				"334|Mairipora                       ",
				"335|Manduri                         ",
				"336|Maraba Paulista                 ",
				"337|Maracai                         ",
				"338|Marapoama                       ",
				"339|Mariapolis                      ",
				"|Marilia                         ",
				"|Marinopolis                     ",
				"|Martinopolis                    ",
				"|Matao                           ",
				"|Maua                            ",
				"|Mendonca                        ",
				"|Meridiano                       ",
				"|Mesopolis                       ",
				"|Miguelopolis                    ",
				"|Mineiros do Tiete               ",
				"|Mira Estrela                    ",
				"|Miracatu                        ",
				"|Mirandopolis                    ",
				"|Mirante do Paranapanema         ",
				"|Mirassol                        ",
				"|Mirassolandia                   ",
				"|Mococa                          ",
				"|Mogi Guacu                      ",
				"|Moji das Cruzes                 ",
				"|Moji-Mirim                      ",
				"|Mombuca                         ",
				"|Moncoes                         ",
				"|Mongagua                        ",
				"|Monte Alegre do Sul             ",
				"|Monte Alto                      ",
				"|Monte Aprazivel                 ",
				"|Monte Azul Paulista             ",
				"|Monte Castelo                   ",
				"|Monte Mor                       ",
				"|Monteiro Lobato                 ",
				"|Morro Agudo                     ",
				"|Morungaba                       ",
				"|Motuca                          ",
				"|Murutinga do Sul                ",
				"|Nantes                          ",
				"|Narandiba                       ",
				"|Natividade da Serra             ",
				"|Nazare Paulista                 ",
				"|Neves Paulista                  ",
				"|Nhandeara                       ",
				"|Nipoa                           ",
				"|Nova Alianca                    ",
				"|Nova Campina                    ",
				"|Nova Canaa Paulista             ",
				"|Nova Castilho                   ",
				"|Nova Europa                     ",
				"|Nova Granada                    ",
				"|Nova Guataporanga               ",
				"|Nova Independencia              ",
				"|Nova Luzitania                  ",
				"|Nova Odessa                     ",
				"|Novais                          ",
				"|Novo Horizonte                  ",
				"|Nuporanga                       ",
				"|Ocaucu                          ",
				"|Oleo                            ",
				"|Olimpia                         ",
				"|Onda Verde                      ",
				"|Oriente                         ",
				"|Orindiuva                       ",
				"|Orlandia                        ",
				"|Osasco                          ",
				"|Oscar Bressane                  ",
				"|Osvaldo Cruz                    ",
				"|Ourinhos                        ",
				"|Ouro Verde                      ",
				"|Ouroeste                        ",
				"|Pacaembu                        ",
				"|Palestina                       ",
				"|Palmares Paulista               ",
				"|Palmeira d'Oeste                ",
				"|Palmital                        ",
				"|Panorama                        ",
				"|Paraguacu Paulista              ",
				"|Paraibuna                       ",
				"|Paraiso                         ",
				"|Paranapanema                    ",
				"|Paranapua                       ",
				"|Parapua                         ",
				"|Pardinho                        ",
				"|Pariquera-Acu                   ",
				"|Parisi                          ",
				"|Patrocinio Paulista             ",
				"|Pauliceia                       ",
				"|Paulinia                        ",
				"|Paulistania                     ",
				"|Paulo de Faria                  ",
				"|Pederneiras                     ",
				"|Pedra Bela                      ",
				"|Pedranopolis                    ",
				"|Pedregulho                      ",
				"|Pedreira                        ",
				"|Pedrinhas Paulista              ",
				"|Pedro de Toledo                 ",
				"|Penapolis                       ",
				"|Pereira Barreto                 ",
				"|Pereiras                        ",
				"|Peruibe                         ",
				"|Piacatu                         ",
				"|Piedade                         ",
				"|Pilar do Sul                    ",
				"|Pindamonhangaba                 ",
				"|Pindorama                       ",
				"|Pinhalzinho                     ",
				"|Piquerobi                       ",
				"|Piquete                         ",
				"|Piracaia                        ",
				"|Piracicaba                      ",
				"|Piraju                          ",
				"|Pirajui                         ",
				"|Pirangi                         ",
				"|Pirapora do Bom Jesus           ",
				"|Pirapozinho                     ",
				"|Pirassununga                    ",
				"|Piratininga                     ",
				"|Pitangueiras                    ",
				"|Planalto                        ",
				"|Platina                         ",
				"|Poa                             ",
				"|Poloni                          ",
				"|Pompeia                         ",
				"|Pongai                          ",
				"|Pontal                          ",
				"|Pontalinda                      ",
				"|Pontes Gestal                   ",
				"|Populina                        ",
				"|Porangaba                       ",
				"|Porto Feliz                     ",
				"|Porto Ferreira                  ",
				"|Potim                           ",
				"|Potirendaba                     ",
				"|Pracinha                        ",
				"|Pradopolis                      ",
				"|Praia Grande                    ",
				"|Pratania                        ",
				"|Presidente Alves                ",
				"|Presidente Bernardes            ",
				"|Presidente Epitacio             ",
				"|Presidente Prudente             ",
				"|Presidente Venceslau            ",
				"|Promissao                       ",
				"|Quadra                          ",
				"|Quata                           ",
				"|Queiroz                         ",
				"|Queluz                          ",
				"|Quintana                        ",
				"|Rafard                          ",
				"|Rancharia                       ",
				"|Redencao da Serra               ",
				"|Regente Feijo                   ",
				"|Reginopolis                     ",
				"|Registro                        ",
				"|Restinga                        ",
				"|Ribeira                         ",
				"|Ribeirao Bonito                 ",
				"|Ribeirao Branco                 ",
				"|Ribeirao Corrente               ",
				"|Ribeirao Grande                 ",
				"|Ribeirao Pires                  ",
				"|Ribeirao Preto                  ",
				"|Ribeirao do Sul                 ",
				"|Ribeirao dos Indios             ",
				"|Rifaina                         ",
				"|Rincao                          ",
				"|Rinopolis                       ",
				"|Rio Claro                       ",
				"|Rio Grande da Serra             ",
				"|Rio das Pedras                  ",
				"|Riolandia                       ",
				"|Riversul                        ",
				"|Rosana                          ",
				"|Roseira                         ",
				"|Rubiacea                        ",
				"|Rubineia                        ",
				"|Sabino                          ",
				"|Sagres                          ",
				"|Sales Oliveira                  ",
				"|Sales                           ",
				"|Salesopolis                     ",
				"|Salmourao                       ",
				"|Saltinho                        ",
				"|Salto Grande                    ",
				"|Salto de Pirapora               ",
				"|Salto                           ",
				"|Sandovalina                     ",
				"|Santa Adelia                    ",
				"|Santa Albertina                 ",
				"|Santa Barbara d'Oeste           ",
				"|Santa Branca                    ",
				"|Santa Clara d'Oeste             ",
				"|Santa Cruz da Conceicao         ",
				"|Santa Cruz da Esperanca         ",
				"|Santa Cruz das Palmeiras        ",
				"|Santa Cruz do Rio Pardo         ",
				"|Santa Ernestina                 ",
				"|Santa Fe do Sul                 ",
				"|Santa Gertrudes                 ",
				"|Santa Isabel                    ",
				"|Santa Lucia                     ",
				"|Santa Maria da Serra            ",
				"|Santa Mercedes                  ",
				"|Santa Rita d'Oeste              ",
				"|Santa Rita do Passa Quatro      ",
				"|Santa Rosa de Viterbo           ",
				"|Santa Salete                    ",
				"|Santana da Ponte Pensa          ",
				"|Santana de Parnaiba             ",
				"|Santo Anastacio                 ",
				"|Santo Andre                     ",
				"|Santo Antonio da Alegria        ",
				"|Santo Antonio de Posse          ",
				"|Santo Antonio do Aracangua      ",
				"|Santo Antonio do Jardim         ",
				"|Santo Antonio do Pinhal         ",
				"|Santo Expedito                  ",
				"|Santopolis do Aguapei           ",
				"|Santos                          ",
				"|Sao Bento do Sapucai            ",
				"|Sao Bernardo do Campo           ",
				"|Sao Caetano do Sul              ",
				"|Sao Carlos                      ",
				"|Sao Francisco                   ",
				"|Sao Joao da Boa Vista           ",
				"|Sao Joao das Duas Pontes        ",
				"|Sao Joao de Iracema             ",
				"|Sao Joao do Pau d'Alho          ",
				"|Sao Joaquim da Barra            ",
				"|Sao Jose da Bela Vista          ",
				"|Sao Jose do Barreiro            ",
				"|Sao Jose do Rio Pardo           ",
				"|Sao Jose do Rio Preto           ",
				"|Sao Jose dos Campos             ",
				"|Sao Lourenco da Serra           ",
				"|Sao Luis do Paraitinga          ",
				"|Sao Manuel                      ",
				"|Sao Miguel Arcanjo              ",
				"|Sao Paulo                       ",
				"|Sao Pedro do Turvo              ",
				"|Sao Pedro                       ",
				"|Sao Roque                       ",
				"|Sao Sebastiao da Grama          ",
				"|Sao Sebastiao                   ",
				"|Sao Simao                       ",
				"|Sao Vicente                     ",
				"|Sarapui                         ",
				"|Sarutaia                        ",
				"|Sebastianopolis do Sul          ",
				"|Serra Azul                      ",
				"|Serra Negra                     ",
				"|Serrana                         ",
				"|Sertaozinho                     ",
				"|Sete Barras                     ",
				"|Severinia                       ",
				"|Silveiras                       ",
				"|Socorro                         ",
				"|Sorocaba                        ",
				"|Sud Mennucci                    ",
				"|Sumare                          ",
				"|Suzanapolis                     ",
				"|Suzano                          ",
				"|Tabapua                         ",
				"|Tabatinga                       ",
				"|Taboao da Serra                 ",
				"|Taciba                          ",
				"|Taguai                          ",
				"|Taiacu                          ",
				"|Taiuva                          ",
				"|Tambau                          ",
				"|Tanabi                          ",
				"|Tapirai                         ",
				"|Tapiratiba                      ",
				"|Taquaral                        ",
				"|Taquaritinga                    ",
				"|Taquarituba                     ",
				"|Taquarivai                      ",
				"|Tarabai                         ",
				"|Taruma                          ",
				"|Tatui                           ",
				"|Taubate                         ",
				"|Tejupa                          ",
				"|Teodoro Sampaio                 ",
				"|Terra Roxa                      ",
				"|Tiete                           ",
				"|Timburi                         ",
				"|Torre de Pedra                  ",
				"|Torrinha                        ",
				"|Trabiju                         ",
				"|Tremembe                        ",
				"|Tres Fronteiras                 ",
				"|Tuiuti                          ",
				"|Tupa                            ",
				"|Tupi Paulista                   ",
				"|Turiuba                         ",
				"|Turmalina                       ",
				"|Ubarana                         ",
				"|Ubatuba                         ",
				"|Ubirajara                       ",
				"|Uchoa                           ",
				"|Uniao Paulista                  ",
				"|Urania                          ",
				"|Uru                             ",
				"|Urupes                          ",
				"|Valentim Gentil                 ",
				"|Valinhos                        ",
				"|Valparaiso                      ",
				"|Vargem Grande Paulista          ",
				"|Vargem Grande do Sul            ",
				"|Vargem                          ",
				"|Varzea Paulista                 ",
				"|Vera Cruz                       ",
				"|Vinhedo                         ",
				"|Viradouro                       ",
				"|Vista Alegre do Alto            ",
				"|Vitoria Brasil                  ",
				"|Votorantim                      ",
				"|Votuporanga                     ",
				"|Zacarias	                     "
				
		);
		return municipios;
	}
	

}


