package br.com.petmooby.core.jobs;

import java.util.Arrays;
import java.util.List;

public class JobCadMunicipiosPernambuco {


	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(

				"1|Afogados da Ingazeira           ",
				"2|Afrânio                         ",
				"3|Agrestina                       ",
				"4|Alagoinha                       ",
				"5|Aliança                         ",
				"6|Altinho                         ",
				"7|Amaraji                         ",
				"8|Angelim                         ",
				"9|Araripina                       ",
				"10|Araçoiaba                       ",
				"11|Arcoverde                       ",
				"12|Barra de Guabiraba              ",
				"13|Barreiros                       ",
				"14|Belo Jardim                     ",
				"15|Belém de Maria                  ",
				"16|Belém de São Francisco          ",
				"17|Betânia                         ",
				"18|Bezerros                        ",
				"19|Bodocó                          ",
				"20|Bom Conselho                    ",
				"21|Bom Jardim                      ",
				"22|Bonito                          ",
				"23|Brejinho                        ",
				"24|Brejo da Madre de Deus          ",
				"25|Brejão                          ",
				"26|Buenos Aires                    ",
				"27|Buíque                          ",
				"28|Cabo de Santo Agostinho         ",
				"29|Cabrobó                         ",
				"30|Cachoeirinha                    ",
				"31|Caetés                          ",
				"32|Calumbi                         ",
				"33|Calçado                         ",
				"34|Camaragibe                      ",
				"35|Camocim de São Félix            ",
				"36|Camutanga                       ",
				"37|Canhotinho                      ",
				"38|Capoeiras                       ",
				"39|Carnaubeira da Penha            ",
				"40|Carnaíba                        ",
				"41|Carpina                         ",
				"42|Caruaru                         ",
				"43|Casinhas                        ",
				"44|Catende                         ",
				"45|Cedro                           ",
				"46|Chã de Alegria                  ",
				"47|Chã Grande                      ",
				"48|Condado                         ",
				"49|Correntes                       ",
				"50|Cortês                          ",
				"51|Cumaru                          ",
				"52|Cupira                          ",
				"53|Custódia                        ",
				"54|Dormentes                       ",
				"55|Escada                          ",
				"56|Exu                             ",
				"57|Feira Nova                      ",
				"58|Fernando de Noronha             ",
				"59|Ferreiros                       ",
				"60|Flores                          ",
				"61|Floresta                        ",
				"62|Frei Miguelinho                 ",
				"63|Gameleira                       ",
				"64|Garanhuns                       ",
				"65|Glória do Goitá                 ",
				"66|Goiana                          ",
				"67|Granito                         ",
				"68|Gravatá                         ",
				"69|Iati                            ",
				"70|Ibimirim                        ",
				"71|Ibirajuba                       ",
				"72|Igarassu                        ",
				"73|Iguaraci                        ",
				"74|Ilha de Itamaracá               ",
				"75|Inajá                           ",
				"76|Ingazeira                       ",
				"77|Ipojuca                         ",
				"78|Ipubi                           ",
				"79|Itacuruba                       ",
				"80|Itambé                          ",
				"81|Itapetim                        ",
				"82|Itapissuma                      ",
				"83|Itaquitinga                     ",
				"84|Itaíba                          ",
				"85|Jaboatão dos Guararapes         ",
				"86|Jaqueira                        ",
				"87|Jataúba                         ",
				"88|Jatobá                          ",
				"89|Joaquim Nabuco                  ",
				"90|João Alfredo                    ",
				"91|Jucati                          ",
				"92|Jupi                            ",
				"93|Jurema                          ",
				"94|Lagoa de Itaenga                ",
				"95|Lagoa do Carro                  ",
				"96|Lagoa do Ouro                   ",
				"97|Lagoa dos Gatos                 ",
				"98|Lagoa Grande                    ",
				"99|Lajedo                          ",
				"100|Limoeiro                        ",
				"101|Macaparana                      ",
				"102|Machados                        ",
				"103|Manari                          ",
				"104|Maraial                         ",
				"105|Mirandiba                       ",
				"106|Moreilândia                     ",
				"107|Moreno                          ",
				"108|Nazaré da Mata                  ",
				"109|Olinda                          ",
				"110|Orobó                           ",
				"111|Orocó                           ",
				"112|Ouricuri                        ",
				"113|Palmares                        ",
				"114|Palmeirina                      ",
				"115|Panelas                         ",
				"116|Paranatama                      ",
				"117|Parnamirim                      ",
				"118|Passira                         ",
				"119|Paudalho                        ",
				"120|Paulista                        ",
				"121|Pedra                           ",
				"122|Pesqueira                       ",
				"123|Petrolina                       ",
				"124|Petrolândia                     ",
				"125|Pombos                          ",
				"126|Poção                           ",
				"127|Primavera                       ",
				"128|Quipapá                         ",
				"129|Quixaba                         ",
				"130|Recife                          ",
				"131|Riacho das Almas                ",
				"132|Ribeirão                        ",
				"133|Rio Formoso                     ",
				"134|Sairé                           ",
				"135|Salgadinho                      ",
				"136|Salgueiro                       ",
				"137|Saloá                           ",
				"138|Sanharó                         ",
				"139|Santa Cruz                      ",
				"140|Santa Cruz da Baixa Verde       ",
				"141|Santa Cruz do Capibaribe        ",
				"142|Santa Filomena                  ",
				"143|Santa Maria da Boa Vista        ",
				"144|Santa Maria do Cambucá          ",
				"145|Santa Terezinha                 ",
				"146|Serra Talhada                   ",
				"147|Serrita                         ",
				"148|Sertânia                        ",
				"149|Sirinhaém                       ",
				"150|Solidão                         ",
				"151|Surubim                         ",
				"152|São Benedito do Sul             ",
				"153|São Bento do Una                ",
				"154|São Caetano                     ",
				"155|São Joaquim do Monte            ",
				"156|São José da Coroa Grande        ",
				"157|São José do Belmonte            ",
				"158|São José do Egito               ",
				"159|São João                        ",
				"160|São Lourenço da Mata            ",
				"161|São Vicente Férrer              ",
				"162|Tabira                          ",
				"163|Tacaimbó                        ",
				"164|Tacaratu                        ",
				"165|Tamandaré                       ",
				"166|Taquaritinga do Norte           ",
				"167|Terezinha                       ",
				"168|Terra Nova                      ",
				"170|Timbaúba                        ",
				"171|Toritama                        ",
				"172|Tracunhaém                      ",
				"173|Trindade                        ",
				"174|Triunfo                         ",
				"175|Tupanatinga                     ",
				"176|Tuparetama                      ",
				"177|Venturosa                       ",
				"178|Verdejante                      ",
				"179|Vertente do Lério               ",
				"180|Vertentes                       ",
				"181|Vicência                        ",
				"182|Vitória de Santo Antão          ",
				"183|Xexéu                           ",
				"184|Água Preta                      ",
				"185|Águas Belas                     "	);
		return municipios;
	}

}
