package br.com.petmooby.core.jobs;

import java.util.Arrays;
import java.util.List;


public class JobCadMunicipiosSaoPaulo {
	
	
	public static List<String> getMunicipios() {
		List<String> municipios = Arrays.asList(	
				"1|Adamantina                      ",
				"2|Adolfo                          ",
				"3|Aguai                           ",
				"4|Aguas da Prata                  ",
				"5|Aguas de Lindoia                ",
				"6|Aguas de Santa Barbara          ",
				"7|Aguas de Sao Pedro              ",
				"8|Agudos                          ",
				"9|Alambari                        ",
				"10|Alfredo Marcondes               ",
				"11|Altair                          ",
				"12|Altinopolis                     ",
				"13|Alto Alegre                     ",
				"14|Aluminio                        ",
				"15|Alvares Florence                ",
				"16|Alvares Machado                 ",
				"17|Alvaro de Carvalho              ",
				"18|Alvinlandia                     ",
				"19|Americana                       ",
				"20|Americo Brasiliense             ",
				"21|Americo de Campos               ",
				"22|Amparo                          ",
				"23|Analandia                       ",
				"24|Andradina                       ",
				"25|Angatuba                        ",
				"26|Anhembi                         ",
				"27|Anhumas                         ",
				"28|Aparecida d'Oeste               ",
				"29|Aparecida                       ",
				"30|Apiai                           ",
				"31|Aracariguama                    ",
				"32|Aracatuba                       ",
				"33|Aracoiaba da Serra              ",
				"34|Aramina                         ",
				"35|Arandu                          ",
				"36|Arapei                          ",
				"37|Araraquara                      ",
				"38|Araras                          ",
				"39|Arco-Iris                       ",
				"40|Arealva                         ",
				"41|Areias                          ",
				"42|Areiopolis                      ",
				"43|Ariranha                        ",
				"44|Artur Nogueira                  ",
				"45|Aruja                           ",
				"46|Aspasia                         ",
				"47|Assis                           ",
				"48|Atibaia                         ",
				"49|Auriflama                       ",
				"51|Avai                            ",
				"52|Avanhandava                     ",
				"53|Avare                           ",
				"54|Bady Bassitt                    ",
				"55|Balbinos                        ",
				"56|Balsamo                         ",
				"57|Bananal                         ",
				"58|Barao de Antonina               ",
				"59|Barbosa                         ",
				"60|Bariri                          ",
				"61|Barra Bonita                    ",
				"62|Barra do Chapeu                 ",
				"63|Barra do Turvo                  ",
				"64|Barretos                        ",
				"65|Barrinha                        ",
				"66|Barueri                         ",
				"67|Bastos                          ",
				"68|Batatais                        ",
				"69|Bauru                           ",
				"70|Bebedouro                       ",
				"71|Bento de Abreu                  ",
				"72|Bernardino de Campos            ",
				"73|Bertioga                        ",
				"74|Bilac                           ",
				"75|Birigui                         ",
				"76|Biritiba-Mirim                  ",
				"77|Boa Esperanca do Sul            ",
				"78|Bocaina                         ",
				"79|Bofete                          ",
				"80|Boituva                         ",
				"81|Bom Jesus dos Perdoes           ",
				"82|Bom Sucesso de Itarare          ",
				"83|Bora                            ",
				"84|Boraceia                        ",
				"85|Borborema                       ",
				"86|Borebi                          ",
				"87|Botucatu                        ",
				"88|Braganca Paulista               ",
				"89|Brauna                          ",
				"91|Brejo Alegre                    ",
				"92|Brodosqui                       ",
				"93|Brotas                          ",
				"94|Buri                            ",
				"95|Buritama                        ",
				"96|Buritizal                       ",
				"97|Cabralia Paulista               ",
				"98|Cabreuva                        ",
				"99|Cacapava                        ",
				"100|Cachoeira Paulista              ",
				"101|Caconde                         ",
				"102|Cafelandia                      ",
				"103|Caiabu                          ",
				"104|Caieiras                        ",
				"105|Caiua                           ",
				"106|Cajamar                         ",
				"107|Cajati                          ",
				"108|Cajobi                          ",
				"109|Cajuru                          ",
				"110|Campina do Monte Alegre         ",
				"111|Campinas                        ",
				"112|Campo Limpo Paulista            ",
				"113|Campos Novos Paulista           ",
				"114|Campos do Jordao                ",
				"115|Cananeia                        ",
				"116|Canas                           ",
				"117|Candido Mota                    ",
				"118|Candido Rodrigues               ",
				"119|Canitar                         ",
				"120|Capao Bonito                    ",
				"121|Capela do Alto                  ",
				"122|Capivari                        ",
				"123|Caraguatatuba                   ",
				"124|Carapicuiba                     ",
				"125|Cardoso                         ",
				"126|Casa Branca                     ",
				"127|Cassia dos Coqueiros            ",
				"128|Castilho                        ",
				"129|Catanduva                       ",
				"130|Catigua                         ",
				"131|Cedral                          ",
				"132|Cerqueira Cesar                 ",
				"133|Cerquilho                       ",
				"134|Cesario Lange                   ",
				"135|Charqueada                      ",
				"136|Chavantes                       ",
				"137|Clementina                      ",
				"138|Colina                          ",
				"139|Colombia                        ",
				"140|Conchal                         ",
				"141|Conchas                         ",
				"142|Cordeiropolis                   ",
				"143|Coroados                        ",
				"144|Coronel Macedo                  ",
				"145|Corumbatai                      ",
				"146|Cosmopolis                      ",
				"147|Cosmorama                       ",
				"148|Cotia                           ",
				"149|Cravinhos                       ",
				"150|Cristais Paulista               ",
				"151|Cruzalia                        ",
				"152|Cruzeiro                        ",
				"153|Cubatao                         ",
				"154|Cunha                           ",
				"155|Descalvado                      ",
				"156|Diadema                         ",
				"157|Dirce Reis                      ",
				"158|Divinolandia                    ",
				"159|Dobrada                         ",
				"160|Dois Corregos                   ",
				"161|Dolcinopolis                    ",
				"162|Dourado                         ",
				"163|Dracena                         ",
				"164|Duartina                        ",
				"165|Dumont                          ",
				"166|Echapora                        ",
				"167|Eldorado                        ",
				"168|Elias Fausto                    ",
				"169|Elisiario                       ",
				"170|Embauba                         ",
				"171|Embu                            ",
				"172|Embu-Guacu                      ",
				"173|Emilianopolis                   ",
				"174|Engenheiro Coelho               ",
				"175|Espirito Santo do Pinhal        ",
				"176|Espirito Santo do Turvo         ",
				"177|Estiva Gerbi                    ",
				"178|Estrela d'Oeste                 ",
				"179|Estrela do Norte                ",
				"180|Euclides da Cunha Paulista      ",
				"181|Fartura                         ",
				"182|Fernando Prestes                ",
				"183|Fernandopolis                   ",
				"184|Fernao                          ",
				"185|Ferraz de Vasconcelos           ",
				"186|Flora Rica                      ",
				"187|Floreal                         ",
				"188|Florida Paulista                ",
				"189|Florinia                        ",
				"190|Franca                          ",
				"191|Francisco Morato                ",
				"192|Franco da Rocha                 ",
				"193|Gabriel Monteiro                ",
				"194|Galia                           ",
				"195|Garca                           ",
				"196|Gastao Vidigal                  ",
				"197|Gaviao Peixoto                  ",
				"198|General Salgado                 ",
				"199|Getulina                        ",
				"200|Glicerio                        ",
				"201|Guaicara                        ",
				"202|Guaimbe                         ",
				"203|Guaira                          ",
				"204|Guapiacu                        ",
				"205|Guapiara                        ",
				"206|Guara							 ",
				"207|Guaracai                        ",
				"208|Guaraci                         ",
				"209|Guarani d'Oeste                 ",
				"210|Guaranta                        ",
				"211|Guararapes                      ",
				"212|Guararema                       ",
				"213|Guaratingueta                   ",
				"214|Guarei                          ",
				"215|Guariba                         ",
				"216|Guaruja                         ",
				"217|Guarulhos                       ",
				"218|Guatapara                       ",
				"219|Guzolandia                      ",
				"220|Herculandia                     ",
				"221|Holambra                        ",
				"222|Hortolandia                     ",
				"223|Iacanga                         ",
				"224|Iacri                           ",
				"225|Iaras                           ",
				"226|Ibate                           ",
				"227|Ibira                           ",
				"228|Ibirarema                       ",
				"229|Ibitinga                        ",
				"230|Ibiuna                          ",
				"231|Icem                            ",
				"232|Iepe                            ",
				"233|Igaracu do Tiete                ",
				"234|Igarapava                       ",
				"235|Igarata                         ",
				"236|Iguape                          ",
				"237|Ilha Comprida                   ",
				"238|Ilha Solteira                   ",
				"239|Ilhabela                        ",
				"240|Indaiatuba                      ",
				"241|Indiana                         ",
				"242|Indiapora                       ",
				"243|Inubia Paulista                 ",
				"244|Ipaucu                          ",
				"245|Ipero                           ",
				"246|Ipeuna                          ",
				"247|Ipigua                          ",
				"248|Iporanga                        ",
				"249|Ipua                            ",
				"250|Iracemapolis                    ",
				"251|Irapua                          ",
				"252|Irapuru                         ",
				"253|Itabera                         ",
				"254|Itai                            ",
				"255|Itajobi                         ",
				"256|Itaju                           ",
				"257|Itanhaem                        ",
				"258|Itaoca                          ",
				"259|Itapecerica da Serra            ",
				"260|Itapetininga                    ",
				"270|Itapeva                         ",
				"271|Itapevi                         ",
				"272|Itapira                         ",
				"273|Itapirapua Paulista             ",
				"274|Itapolis                        ",
				"275|Itaporanga                      ",
				"276|Itapui                          ",
				"277|Itapura                         ",
				"278|Itaquaquecetuba                 ",
				"279|Itarare                         ",
				"280|Itariri                         ",
				"281|Itatiba                         ",
				"282|Itatinga                        ",
				"283|Itirapina                       ",
				"284|Itirapua                        ",
				"285|Itobi                           ",
				"286|Itu                             ",
				"287|Itupeva                         ",
				"288|Ituverava                       ",
				"289|Jaborandi                       ",
				"290|Jaboticabal                     ",
				"291|Jacarei                         ",
				"292|Jaci                            ",
				"293|Jacupiranga                     ",
				"294|Jaguariuna                      ",
				"295|Jales                           ",
				"296|Jambeiro                        ",
				"297|Jandira                         ",
				"298|Jardinopolis                    ",
				"299|Jarinu                          ",
				"300|Jau                             ",
				"301|Jeriquara                       ",
				"302|Joanopolis                      ",
				"303|Joao Ramalho                    ",
				"304|Jose Bonifacio                  ",
				"305|Julio Mesquita                  ",
				"306|Jumirim                         ",
				"307|Jundiai                         ",
				"308|Junqueiropolis                  ",
				"309|Juquia                          ",
				"310|Juquitiba                       ",
				"311|Lagoinha                        ",
				"312|Laranjal Paulista               ",
				"313|Lavinia                         ",
				"314|Lavrinhas                       ",
				"315|Leme                            ",
				"316|Lencois Paulista                ",
				"317|Limeira                         ",
				"318|Lindoia                         ",
				"319|Lins                            ",
				"320|Lorena                          ",
				"321|Lourdes                         ",
				"322|Louveira                        ",
				"323|Lucelia                         ",
				"324|Lucianopolis                    ",
				"325|Luis Antonio                    ",
				"326|Luiziania                       ",
				"327|Lupercio                        ",
				"328|Lutecia                         ",
				"329|Macatuba                        ",
				"330|Macaubal                        ",
				"331|Macedonia                       ",
				"332|Magda                           ",
				"333|Mairinque                       ",
				"334|Mairipora                       ",
				"335|Manduri                         ",
				"336|Maraba Paulista                 ",
				"337|Maracai                         ",
				"338|Marapoama                       ",
				"339|Mariapolis                      ",
				"400|Marilia                         ",
				"401|Marinopolis                     ",
				"402|Martinopolis                    ",
				"403|Matao                           ",
				"404|Maua                            ",
				"405|Mendonca                        ",
				"406|Meridiano                       ",
				"407|Mesopolis                       ",
				"408|Miguelopolis                    ",
				"409|Mineiros do Tiete               ",
				"410|Mira Estrela                    ",
				"411|Miracatu                        ",
				"412|Mirandopolis                    ",
				"413|Mirante do Paranapanema         ",
				"414|Mirassol                        ",
				"415|Mirassolandia                   ",
				"416|Mococa                          ",
				"417|Mogi Guacu                      ",
				"418|Moji das Cruzes                 ",
				"419|Moji-Mirim                      ",
				"420|Mombuca                         ",
				"421|Moncoes                         ",
				"422|Mongagua                        ",
				"423|Monte Alegre do Sul             ",
				"424|Monte Alto                      ",
				"425|Monte Aprazivel                 ",
				"426|Monte Azul Paulista             ",
				"427|Monte Castelo                   ",
				"428|Monte Mor                       ",
				"429|Monteiro Lobato                 ",
				"430|Morro Agudo                     ",
				"431|Morungaba                       ",
				"432|Motuca                          ",
				"433|Murutinga do Sul                ",
				"434|Nantes                          ",
				"435|Narandiba                       ",
				"436|Natividade da Serra             ",
				"437|Nazare Paulista                 ",
				"438|Neves Paulista                  ",
				"439|Nhandeara                       ",
				"440|Nipoa                           ",
				"441|Nova Alianca                    ",
				"442|Nova Campina                    ",
				"443|Nova Canaa Paulista             ",
				"444|Nova Castilho                   ",
				"445|Nova Europa                     ",
				"446|Nova Granada                    ",
				"447|Nova Guataporanga               ",
				"448|Nova Independencia              ",
				"449|Nova Luzitania                  ",
				"500|Nova Odessa                     ",
				"501|Novais                          ",
				"502|Novo Horizonte                  ",
				"503|Nuporanga                       ",
				"504|Ocaucu                          ",
				"505|Oleo                            ",
				"506|Olimpia                         ",
				"507|Onda Verde                      ",
				"508|Oriente                         ",
				"509|Orindiuva                       ",
				"510|Orlandia                        ",
				"511|Osasco                          ",
				"512|Oscar Bressane                  ",
				"513|Osvaldo Cruz                    ",
				"514|Ourinhos                        ",
				"515|Ouro Verde                      ",
				"516|Ouroeste                        ",
				"517|Pacaembu                        ",
				"518|Palestina                       ",
				"519|Palmares Paulista               ",
				"520|Palmeira d'Oeste                ",
				"521|Palmital                        ",
				"522|Panorama                        ",
				"523|Paraguacu Paulista              ",
				"524|Paraibuna                       ",
				"525|Paraiso                         ",
				"526|Paranapanema                    ",
				"527|Paranapua                       ",
				"528|Parapua                         ",
				"529|Pardinho                        ",
				"530|Pariquera-Acu                   ",
				"531|Parisi                          ",
				"532|Patrocinio Paulista             ",
				"533|Pauliceia                       ",
				"534|Paulinia                        ",
				"535|Paulistania                     ",
				"536|Paulo de Faria                  ",
				"537|Pederneiras                     ",
				"538|Pedra Bela                      ",
				"539|Pedranopolis                    ",
				"540|Pedregulho                      ",
				"541|Pedreira                        ",
				"542|Pedrinhas Paulista              ",
				"543|Pedro de Toledo                 ",
				"544|Penapolis                       ",
				"545|Pereira Barreto                 ",
				"546|Pereiras                        ",
				"547|Peruibe                         ",
				"548|Piacatu                         ",
				"549|Piedade                         ",
				"550|Pilar do Sul                    ",
				"551|Pindamonhangaba                 ",
				"552|Pindorama                       ",
				"553|Pinhalzinho                     ",
				"554|Piquerobi                       ",
				"555|Piquete                         ",
				"556|Piracaia                        ",
				"557|Piracicaba                      ",
				"558|Piraju                          ",
				"559|Pirajui                         ",
				"560|Pirangi                         ",
				"561|Pirapora do Bom Jesus           ",
				"562|Pirapozinho                     ",
				"563|Pirassununga                    ",
				"564|Piratininga                     ",
				"565|Pitangueiras                    ",
				"566|Planalto                        ",
				"567|Platina                         ",
				"568|Poa                             ",
				"569|Poloni                          ",
				"570|Pompeia                         ",
				"571|Pongai                          ",
				"572|Pontal                          ",
				"573|Pontalinda                      ",
				"574|Pontes Gestal                   ",
				"575|Populina                        ",
				"576|Porangaba                       ",
				"577|Porto Feliz                     ",
				"578|Porto Ferreira                  ",
				"579|Potim                           ",
				"580|Potirendaba                     ",
				"581|Pracinha                        ",
				"582|Pradopolis                      ",
				"583|Praia Grande                    ",
				"584|Pratania                        ",
				"585|Presidente Alves                ",
				"586|Presidente Bernardes            ",
				"587|Presidente Epitacio             ",
				"588|Presidente Prudente             ",
				"589|Presidente Venceslau            ",
				"590|Promissao                       ",
				"591|Quadra                          ",
				"592|Quata                           ",
				"593|Queiroz                         ",
				"594|Queluz                          ",
				"595|Quintana                        ",
				"596|Rafard                          ",
				"597|Rancharia                       ",
				"598|Redencao da Serra               ",
				"599|Regente Feijo                   ",
				"600|Reginopolis                     ",
				"601|Registro                        ",
				"602|Restinga                        ",
				"603|Ribeira                         ",
				"604|Ribeirao Bonito                 ",
				"605|Ribeirao Branco                 ",
				"606|Ribeirao Corrente               ",
				"607|Ribeirao Grande                 ",
				"608|Ribeirao Pires                  ",
				"609|Ribeirao Preto                  ",
				"610|Ribeirao do Sul                 ",
				"611|Ribeirao dos Indios             ",
				"612|Rifaina                         ",
				"613|Rincao                          ",
				"614|Rinopolis                       ",
				"615|Rio Claro                       ",
				"616|Rio Grande da Serra             ",
				"617|Rio das Pedras                  ",
				"618|Riolandia                       ",
				"619|Riversul                        ",
				"620|Rosana                          ",
				"621|Roseira                         ",
				"622|Rubiacea                        ",
				"623|Rubineia                        ",
				"624|Sabino                          ",
				"625|Sagres                          ",
				"626|Sales Oliveira                  ",
				"627|Sales                           ",
				"628|Salesopolis                     ",
				"629|Salmourao                       ",
				"630|Saltinho                        ",
				"631|Salto Grande                    ",
				"632|Salto de Pirapora               ",
				"633|Salto                           ",
				"634|Sandovalina                     ",
				"635|Santa Adelia                    ",
				"636|Santa Albertina                 ",
				"637|Santa Barbara d'Oeste           ",
				"638|Santa Branca                    ",
				"639|Santa Clara d'Oeste             ",
				"640|Santa Cruz da Conceicao         ",
				"641|Santa Cruz da Esperanca         ",
				"642|Santa Cruz das Palmeiras        ",
				"643|Santa Cruz do Rio Pardo         ",
				"644|Santa Ernestina                 ",
				"645|Santa Fe do Sul                 ",
				"646|Santa Gertrudes                 ",
				"647|Santa Isabel                    ",
				"648|Santa Lucia                     ",
				"649|Santa Maria da Serra            ",
				"650|Santa Mercedes                  ",
				"651|Santa Rita d'Oeste              ",
				"652|Santa Rita do Passa Quatro      ",
				"653|Santa Rosa de Viterbo           ",
				"654|Santa Salete                    ",
				"655|Santana da Ponte Pensa          ",
				"656|Santana de Parnaiba             ",
				"657|Santo Anastacio                 ",
				"658|Santo Andre                     ",
				"659|Santo Antonio da Alegria        ",
				"660|Santo Antonio de Posse          ",
				"661|Santo Antonio do Aracangua      ",
				"662|Santo Antonio do Jardim         ",
				"663|Santo Antonio do Pinhal         ",
				"664|Santo Expedito                  ",
				"665|Santopolis do Aguapei           ",
				"666|Santos                          ",
				"667|Sao Bento do Sapucai            ",
				"668|Sao Bernardo do Campo           ",
				"669|Sao Caetano do Sul              ",
				"670|Sao Carlos                      ",
				"671|Sao Francisco                   ",
				"672|Sao Joao da Boa Vista           ",
				"673|Sao Joao das Duas Pontes        ",
				"674|Sao Joao de Iracema             ",
				"675|Sao Joao do Pau d'Alho          ",
				"676|Sao Joaquim da Barra            ",
				"677|Sao Jose da Bela Vista          ",
				"678|Sao Jose do Barreiro            ",
				"679|Sao Jose do Rio Pardo           ",
				"680|Sao Jose do Rio Preto           ",
				"681|Sao Jose dos Campos             ",
				"682|Sao Lourenco da Serra           ",
				"683|Sao Luis do Paraitinga          ",
				"684|Sao Manuel                      ",
				"685|Sao Miguel Arcanjo              ",
				"686|Sao Paulo                       ",
				"687|Sao Pedro do Turvo              ",
				"688|Sao Pedro                       ",
				"689|Sao Roque                       ",
				"690|Sao Sebastiao da Grama          ",
				"691|Sao Sebastiao                   ",
				"692|Sao Simao                       ",
				"693|Sao Vicente                     ",
				"694|Sarapui                         ",
				"695|Sarutaia                        ",
				"696|Sebastianopolis do Sul          ",
				"697|Serra Azul                      ",
				"698|Serra Negra                     ",
				"699|Serrana                         ",
				"700|Sertaozinho                     ",
				"701|Sete Barras                     ",
				"702|Severinia                       ",
				"703|Silveiras                       ",
				"704|Socorro                         ",
				"705|Sorocaba                        ",
				"706|Sud Mennucci                    ",
				"707|Sumare                          ",
				"708|Suzanapolis                     ",
				"709|Suzano                          ",
				"710|Tabapua                         ",
				"711|Tabatinga                       ",
				"712|Taboao da Serra                 ",
				"713|Taciba                          ",
				"714|Taguai                          ",
				"715|Taiacu                          ",
				"716|Taiuva                          ",
				"717|Tambau                          ",
				"718|Tanabi                          ",
				"719|Tapirai                         ",
				"720|Tapiratiba                      ",
				"721|Taquaral                        ",
				"722|Taquaritinga                    ",
				"723|Taquarituba                     ",
				"724|Taquarivai                      ",
				"725|Tarabai                         ",
				"726|Taruma                          ",
				"727|Tatui                           ",
				"728|Taubate                         ",
				"729|Tejupa                          ",
				"730|Teodoro Sampaio                 ",
				"731|Terra Roxa                      ",
				"732|Tiete                           ",
				"733|Timburi                         ",
				"734|Torre de Pedra                  ",
				"735|Torrinha                        ",
				"736|Trabiju                         ",
				"737|Tremembe                        ",
				"738|Tres Fronteiras                 ",
				"739|Tuiuti                          ",
				"740|Tupa                            ",
				"741|Tupi Paulista                   ",
				"742|Turiuba                         ",
				"743|Turmalina                       ",
				"744|Ubarana                         ",
				"745|Ubatuba                         ",
				"746|Ubirajara                       ",
				"747|Uchoa                           ",
				"748|Uniao Paulista                  ",
				"749|Urania                          ",
				"750|Uru                             ",
				"751|Urupes                          ",
				"752|Valentim Gentil                 ",
				"753|Valinhos                        ",
				"754|Valparaiso                      ",
				"755|Vargem Grande Paulista          ",
				"756|Vargem Grande do Sul            ",
				"757|Vargem                          ",
				"758|Varzea Paulista                 ",
				"759|Vera Cruz                       ",
				"760|Vinhedo                         ",
				"761|Viradouro                       ",
				"762|Vista Alegre do Alto            ",
				"763|Vitoria Brasil                  ",
				"764|Votorantim                      ",
				"765|Votuporanga                     ",
				"766|Zacarias	                     "
				
		);
		return municipios;
	}
	

}


